// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1/generated.proto

package v1

import (
	fmt "fmt"

	v1 "github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/meta/v1"
	proto "github.com/gogo/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *ClientIPConfig) Reset()         { *m = ClientIPConfig{} }
func (m *ClientIPConfig) String() string { return proto.CompactTextString(m) }
func (*ClientIPConfig) ProtoMessage()    {}
func (*ClientIPConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{0}
}
func (m *ClientIPConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientIPConfig.Unmarshal(m, b)
}
func (m *ClientIPConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientIPConfig.Marshal(b, m, deterministic)
}
func (m *ClientIPConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientIPConfig.Merge(m, src)
}
func (m *ClientIPConfig) XXX_Size() int {
	return xxx_messageInfo_ClientIPConfig.Size(m)
}
func (m *ClientIPConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientIPConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClientIPConfig proto.InternalMessageInfo

func (m *ClientIPConfig) GetTimeoutSeconds() int32 {
	if m != nil && m.TimeoutSeconds != nil {
		return *m.TimeoutSeconds
	}
	return 0
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{1}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Container) GetImage() string {
	if m != nil && m.Image != nil {
		return *m.Image
	}
	return ""
}

func (m *Container) GetPorts() []*ContainerPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *Container) GetVolumeMounts() []*VolumeMount {
	if m != nil {
		return m.VolumeMounts
	}
	return nil
}

func (m *ContainerPort) Reset()         { *m = ContainerPort{} }
func (m *ContainerPort) String() string { return proto.CompactTextString(m) }
func (*ContainerPort) ProtoMessage()    {}
func (*ContainerPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{2}
}
func (m *ContainerPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerPort.Unmarshal(m, b)
}
func (m *ContainerPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerPort.Marshal(b, m, deterministic)
}
func (m *ContainerPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerPort.Merge(m, src)
}
func (m *ContainerPort) XXX_Size() int {
	return xxx_messageInfo_ContainerPort.Size(m)
}
func (m *ContainerPort) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerPort.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerPort proto.InternalMessageInfo

func (m *ContainerPort) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ContainerPort) GetHostPort() int32 {
	if m != nil && m.HostPort != nil {
		return *m.HostPort
	}
	return 0
}

func (m *ContainerPort) GetContainerPort() int32 {
	if m != nil && m.ContainerPort != nil {
		return *m.ContainerPort
	}
	return 0
}

func (m *ContainerPort) GetProtocol() string {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return ""
}

func (m *ContainerPort) GetHostIP() string {
	if m != nil && m.HostIP != nil {
		return *m.HostIP
	}
	return ""
}

func (m *ContainerState) Reset()         { *m = ContainerState{} }
func (m *ContainerState) String() string { return proto.CompactTextString(m) }
func (*ContainerState) ProtoMessage()    {}
func (*ContainerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{3}
}
func (m *ContainerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerState.Unmarshal(m, b)
}
func (m *ContainerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerState.Marshal(b, m, deterministic)
}
func (m *ContainerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerState.Merge(m, src)
}
func (m *ContainerState) XXX_Size() int {
	return xxx_messageInfo_ContainerState.Size(m)
}
func (m *ContainerState) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerState.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerState proto.InternalMessageInfo

func (m *ContainerState) GetRunning() *ContainerStateRunning {
	if m != nil {
		return m.Running
	}
	return nil
}

func (m *ContainerStateRunning) Reset()         { *m = ContainerStateRunning{} }
func (m *ContainerStateRunning) String() string { return proto.CompactTextString(m) }
func (*ContainerStateRunning) ProtoMessage()    {}
func (*ContainerStateRunning) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{4}
}
func (m *ContainerStateRunning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerStateRunning.Unmarshal(m, b)
}
func (m *ContainerStateRunning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerStateRunning.Marshal(b, m, deterministic)
}
func (m *ContainerStateRunning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerStateRunning.Merge(m, src)
}
func (m *ContainerStateRunning) XXX_Size() int {
	return xxx_messageInfo_ContainerStateRunning.Size(m)
}
func (m *ContainerStateRunning) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerStateRunning.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerStateRunning proto.InternalMessageInfo

func (m *ContainerStateRunning) GetStartedAt() *v1.Time {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

func (m *ContainerStatus) Reset()         { *m = ContainerStatus{} }
func (m *ContainerStatus) String() string { return proto.CompactTextString(m) }
func (*ContainerStatus) ProtoMessage()    {}
func (*ContainerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{5}
}
func (m *ContainerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerStatus.Unmarshal(m, b)
}
func (m *ContainerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerStatus.Marshal(b, m, deterministic)
}
func (m *ContainerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerStatus.Merge(m, src)
}
func (m *ContainerStatus) XXX_Size() int {
	return xxx_messageInfo_ContainerStatus.Size(m)
}
func (m *ContainerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerStatus proto.InternalMessageInfo

func (m *ContainerStatus) GetState() *ContainerState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *ContainerStatus) GetContainerID() string {
	if m != nil && m.ContainerID != nil {
		return *m.ContainerID
	}
	return ""
}

func (m *EndpointAddress) Reset()         { *m = EndpointAddress{} }
func (m *EndpointAddress) String() string { return proto.CompactTextString(m) }
func (*EndpointAddress) ProtoMessage()    {}
func (*EndpointAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{6}
}
func (m *EndpointAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointAddress.Unmarshal(m, b)
}
func (m *EndpointAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointAddress.Marshal(b, m, deterministic)
}
func (m *EndpointAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointAddress.Merge(m, src)
}
func (m *EndpointAddress) XXX_Size() int {
	return xxx_messageInfo_EndpointAddress.Size(m)
}
func (m *EndpointAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointAddress.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointAddress proto.InternalMessageInfo

func (m *EndpointAddress) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *EndpointAddress) GetNodeName() string {
	if m != nil && m.NodeName != nil {
		return *m.NodeName
	}
	return ""
}

func (m *EndpointPort) Reset()         { *m = EndpointPort{} }
func (m *EndpointPort) String() string { return proto.CompactTextString(m) }
func (*EndpointPort) ProtoMessage()    {}
func (*EndpointPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{7}
}
func (m *EndpointPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointPort.Unmarshal(m, b)
}
func (m *EndpointPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointPort.Marshal(b, m, deterministic)
}
func (m *EndpointPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointPort.Merge(m, src)
}
func (m *EndpointPort) XXX_Size() int {
	return xxx_messageInfo_EndpointPort.Size(m)
}
func (m *EndpointPort) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointPort.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointPort proto.InternalMessageInfo

func (m *EndpointPort) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *EndpointPort) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *EndpointPort) GetProtocol() string {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return ""
}

func (m *EndpointSubset) Reset()         { *m = EndpointSubset{} }
func (m *EndpointSubset) String() string { return proto.CompactTextString(m) }
func (*EndpointSubset) ProtoMessage()    {}
func (*EndpointSubset) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{8}
}
func (m *EndpointSubset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointSubset.Unmarshal(m, b)
}
func (m *EndpointSubset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointSubset.Marshal(b, m, deterministic)
}
func (m *EndpointSubset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointSubset.Merge(m, src)
}
func (m *EndpointSubset) XXX_Size() int {
	return xxx_messageInfo_EndpointSubset.Size(m)
}
func (m *EndpointSubset) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointSubset.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointSubset proto.InternalMessageInfo

func (m *EndpointSubset) GetAddresses() []*EndpointAddress {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *EndpointSubset) GetPorts() []*EndpointPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *Endpoints) Reset()         { *m = Endpoints{} }
func (m *Endpoints) String() string { return proto.CompactTextString(m) }
func (*Endpoints) ProtoMessage()    {}
func (*Endpoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{9}
}
func (m *Endpoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoints.Unmarshal(m, b)
}
func (m *Endpoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoints.Marshal(b, m, deterministic)
}
func (m *Endpoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoints.Merge(m, src)
}
func (m *Endpoints) XXX_Size() int {
	return xxx_messageInfo_Endpoints.Size(m)
}
func (m *Endpoints) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoints.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoints proto.InternalMessageInfo

func (m *Endpoints) GetMetadata() *v1.ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Endpoints) GetSubsets() []*EndpointSubset {
	if m != nil {
		return m.Subsets
	}
	return nil
}

func (m *EndpointsList) Reset()         { *m = EndpointsList{} }
func (m *EndpointsList) String() string { return proto.CompactTextString(m) }
func (*EndpointsList) ProtoMessage()    {}
func (*EndpointsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{10}
}
func (m *EndpointsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointsList.Unmarshal(m, b)
}
func (m *EndpointsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointsList.Marshal(b, m, deterministic)
}
func (m *EndpointsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointsList.Merge(m, src)
}
func (m *EndpointsList) XXX_Size() int {
	return xxx_messageInfo_EndpointsList.Size(m)
}
func (m *EndpointsList) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointsList.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointsList proto.InternalMessageInfo

func (m *EndpointsList) GetMetadata() *v1.ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *EndpointsList) GetItems() []*Endpoints {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *LoadBalancerIngress) Reset()         { *m = LoadBalancerIngress{} }
func (m *LoadBalancerIngress) String() string { return proto.CompactTextString(m) }
func (*LoadBalancerIngress) ProtoMessage()    {}
func (*LoadBalancerIngress) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{11}
}
func (m *LoadBalancerIngress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBalancerIngress.Unmarshal(m, b)
}
func (m *LoadBalancerIngress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBalancerIngress.Marshal(b, m, deterministic)
}
func (m *LoadBalancerIngress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBalancerIngress.Merge(m, src)
}
func (m *LoadBalancerIngress) XXX_Size() int {
	return xxx_messageInfo_LoadBalancerIngress.Size(m)
}
func (m *LoadBalancerIngress) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBalancerIngress.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBalancerIngress proto.InternalMessageInfo

func (m *LoadBalancerIngress) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *LoadBalancerIngress) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *LoadBalancerIngress) GetIpMode() string {
	if m != nil && m.IpMode != nil {
		return *m.IpMode
	}
	return ""
}

func (m *LoadBalancerIngress) GetPorts() []*PortStatus {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *LoadBalancerStatus) Reset()         { *m = LoadBalancerStatus{} }
func (m *LoadBalancerStatus) String() string { return proto.CompactTextString(m) }
func (*LoadBalancerStatus) ProtoMessage()    {}
func (*LoadBalancerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{12}
}
func (m *LoadBalancerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadBalancerStatus.Unmarshal(m, b)
}
func (m *LoadBalancerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadBalancerStatus.Marshal(b, m, deterministic)
}
func (m *LoadBalancerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadBalancerStatus.Merge(m, src)
}
func (m *LoadBalancerStatus) XXX_Size() int {
	return xxx_messageInfo_LoadBalancerStatus.Size(m)
}
func (m *LoadBalancerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadBalancerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_LoadBalancerStatus proto.InternalMessageInfo

func (m *LoadBalancerStatus) GetIngress() []*LoadBalancerIngress {
	if m != nil {
		return m.Ingress
	}
	return nil
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{13}
}
func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (m *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(m, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetMetadata() *v1.ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *NamespaceList) Reset()         { *m = NamespaceList{} }
func (m *NamespaceList) String() string { return proto.CompactTextString(m) }
func (*NamespaceList) ProtoMessage()    {}
func (*NamespaceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{14}
}
func (m *NamespaceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceList.Unmarshal(m, b)
}
func (m *NamespaceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceList.Marshal(b, m, deterministic)
}
func (m *NamespaceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceList.Merge(m, src)
}
func (m *NamespaceList) XXX_Size() int {
	return xxx_messageInfo_NamespaceList.Size(m)
}
func (m *NamespaceList) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceList.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceList proto.InternalMessageInfo

func (m *NamespaceList) GetMetadata() *v1.ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *NamespaceList) GetItems() []*Namespace {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{15}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetMetadata() *v1.ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Node) GetSpec() *NodeSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Node) GetStatus() *NodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *NodeAddress) Reset()         { *m = NodeAddress{} }
func (m *NodeAddress) String() string { return proto.CompactTextString(m) }
func (*NodeAddress) ProtoMessage()    {}
func (*NodeAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{16}
}
func (m *NodeAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeAddress.Unmarshal(m, b)
}
func (m *NodeAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeAddress.Marshal(b, m, deterministic)
}
func (m *NodeAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAddress.Merge(m, src)
}
func (m *NodeAddress) XXX_Size() int {
	return xxx_messageInfo_NodeAddress.Size(m)
}
func (m *NodeAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAddress.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAddress proto.InternalMessageInfo

func (m *NodeAddress) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *NodeAddress) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *NodeCondition) Reset()         { *m = NodeCondition{} }
func (m *NodeCondition) String() string { return proto.CompactTextString(m) }
func (*NodeCondition) ProtoMessage()    {}
func (*NodeCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{17}
}
func (m *NodeCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeCondition.Unmarshal(m, b)
}
func (m *NodeCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeCondition.Marshal(b, m, deterministic)
}
func (m *NodeCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeCondition.Merge(m, src)
}
func (m *NodeCondition) XXX_Size() int {
	return xxx_messageInfo_NodeCondition.Size(m)
}
func (m *NodeCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeCondition.DiscardUnknown(m)
}

var xxx_messageInfo_NodeCondition proto.InternalMessageInfo

func (m *NodeCondition) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *NodeCondition) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *NodeCondition) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

func (m *NodeList) Reset()         { *m = NodeList{} }
func (m *NodeList) String() string { return proto.CompactTextString(m) }
func (*NodeList) ProtoMessage()    {}
func (*NodeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{18}
}
func (m *NodeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeList.Unmarshal(m, b)
}
func (m *NodeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeList.Marshal(b, m, deterministic)
}
func (m *NodeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeList.Merge(m, src)
}
func (m *NodeList) XXX_Size() int {
	return xxx_messageInfo_NodeList.Size(m)
}
func (m *NodeList) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeList.DiscardUnknown(m)
}

var xxx_messageInfo_NodeList proto.InternalMessageInfo

func (m *NodeList) GetMetadata() *v1.ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *NodeList) GetItems() []*Node {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *NodeSpec) Reset()         { *m = NodeSpec{} }
func (m *NodeSpec) String() string { return proto.CompactTextString(m) }
func (*NodeSpec) ProtoMessage()    {}
func (*NodeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{19}
}
func (m *NodeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeSpec.Unmarshal(m, b)
}
func (m *NodeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeSpec.Marshal(b, m, deterministic)
}
func (m *NodeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeSpec.Merge(m, src)
}
func (m *NodeSpec) XXX_Size() int {
	return xxx_messageInfo_NodeSpec.Size(m)
}
func (m *NodeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_NodeSpec proto.InternalMessageInfo

func (m *NodeSpec) GetPodCIDR() string {
	if m != nil && m.PodCIDR != nil {
		return *m.PodCIDR
	}
	return ""
}

func (m *NodeSpec) GetPodCIDRs() []string {
	if m != nil {
		return m.PodCIDRs
	}
	return nil
}

func (m *NodeSpec) GetProviderID() string {
	if m != nil && m.ProviderID != nil {
		return *m.ProviderID
	}
	return ""
}

func (m *NodeSpec) GetTaints() []*Taint {
	if m != nil {
		return m.Taints
	}
	return nil
}

func (m *NodeStatus) Reset()         { *m = NodeStatus{} }
func (m *NodeStatus) String() string { return proto.CompactTextString(m) }
func (*NodeStatus) ProtoMessage()    {}
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{20}
}
func (m *NodeStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStatus.Unmarshal(m, b)
}
func (m *NodeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStatus.Marshal(b, m, deterministic)
}
func (m *NodeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatus.Merge(m, src)
}
func (m *NodeStatus) XXX_Size() int {
	return xxx_messageInfo_NodeStatus.Size(m)
}
func (m *NodeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatus proto.InternalMessageInfo

func (m *NodeStatus) GetConditions() []*NodeCondition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *NodeStatus) GetAddresses() []*NodeAddress {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Pod) Reset()         { *m = Pod{} }
func (m *Pod) String() string { return proto.CompactTextString(m) }
func (*Pod) ProtoMessage()    {}
func (*Pod) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{21}
}
func (m *Pod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pod.Unmarshal(m, b)
}
func (m *Pod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pod.Marshal(b, m, deterministic)
}
func (m *Pod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pod.Merge(m, src)
}
func (m *Pod) XXX_Size() int {
	return xxx_messageInfo_Pod.Size(m)
}
func (m *Pod) XXX_DiscardUnknown() {
	xxx_messageInfo_Pod.DiscardUnknown(m)
}

var xxx_messageInfo_Pod proto.InternalMessageInfo

func (m *Pod) GetMetadata() *v1.ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Pod) GetSpec() *PodSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Pod) GetStatus() *PodStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PodCondition) Reset()         { *m = PodCondition{} }
func (m *PodCondition) String() string { return proto.CompactTextString(m) }
func (*PodCondition) ProtoMessage()    {}
func (*PodCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{22}
}
func (m *PodCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodCondition.Unmarshal(m, b)
}
func (m *PodCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodCondition.Marshal(b, m, deterministic)
}
func (m *PodCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodCondition.Merge(m, src)
}
func (m *PodCondition) XXX_Size() int {
	return xxx_messageInfo_PodCondition.Size(m)
}
func (m *PodCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_PodCondition.DiscardUnknown(m)
}

var xxx_messageInfo_PodCondition proto.InternalMessageInfo

func (m *PodCondition) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *PodCondition) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *PodCondition) GetLastProbeTime() *v1.Time {
	if m != nil {
		return m.LastProbeTime
	}
	return nil
}

func (m *PodCondition) GetLastTransitionTime() *v1.Time {
	if m != nil {
		return m.LastTransitionTime
	}
	return nil
}

func (m *PodCondition) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

func (m *PodCondition) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *PodIP) Reset()         { *m = PodIP{} }
func (m *PodIP) String() string { return proto.CompactTextString(m) }
func (*PodIP) ProtoMessage()    {}
func (*PodIP) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{23}
}
func (m *PodIP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodIP.Unmarshal(m, b)
}
func (m *PodIP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodIP.Marshal(b, m, deterministic)
}
func (m *PodIP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodIP.Merge(m, src)
}
func (m *PodIP) XXX_Size() int {
	return xxx_messageInfo_PodIP.Size(m)
}
func (m *PodIP) XXX_DiscardUnknown() {
	xxx_messageInfo_PodIP.DiscardUnknown(m)
}

var xxx_messageInfo_PodIP proto.InternalMessageInfo

func (m *PodIP) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *PodList) Reset()         { *m = PodList{} }
func (m *PodList) String() string { return proto.CompactTextString(m) }
func (*PodList) ProtoMessage()    {}
func (*PodList) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{24}
}
func (m *PodList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodList.Unmarshal(m, b)
}
func (m *PodList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodList.Marshal(b, m, deterministic)
}
func (m *PodList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodList.Merge(m, src)
}
func (m *PodList) XXX_Size() int {
	return xxx_messageInfo_PodList.Size(m)
}
func (m *PodList) XXX_DiscardUnknown() {
	xxx_messageInfo_PodList.DiscardUnknown(m)
}

var xxx_messageInfo_PodList proto.InternalMessageInfo

func (m *PodList) GetMetadata() *v1.ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *PodList) GetItems() []*Pod {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *PodSpec) Reset()         { *m = PodSpec{} }
func (m *PodSpec) String() string { return proto.CompactTextString(m) }
func (*PodSpec) ProtoMessage()    {}
func (*PodSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{25}
}
func (m *PodSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodSpec.Unmarshal(m, b)
}
func (m *PodSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodSpec.Marshal(b, m, deterministic)
}
func (m *PodSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodSpec.Merge(m, src)
}
func (m *PodSpec) XXX_Size() int {
	return xxx_messageInfo_PodSpec.Size(m)
}
func (m *PodSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_PodSpec.DiscardUnknown(m)
}

var xxx_messageInfo_PodSpec proto.InternalMessageInfo

func (m *PodSpec) GetInitContainers() []*Container {
	if m != nil {
		return m.InitContainers
	}
	return nil
}

func (m *PodSpec) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *PodSpec) GetServiceAccountName() string {
	if m != nil && m.ServiceAccountName != nil {
		return *m.ServiceAccountName
	}
	return ""
}

func (m *PodSpec) GetNodeName() string {
	if m != nil && m.NodeName != nil {
		return *m.NodeName
	}
	return ""
}

func (m *PodSpec) GetHostNetwork() bool {
	if m != nil && m.HostNetwork != nil {
		return *m.HostNetwork
	}
	return false
}

func (m *PodStatus) Reset()         { *m = PodStatus{} }
func (m *PodStatus) String() string { return proto.CompactTextString(m) }
func (*PodStatus) ProtoMessage()    {}
func (*PodStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{26}
}
func (m *PodStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodStatus.Unmarshal(m, b)
}
func (m *PodStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodStatus.Marshal(b, m, deterministic)
}
func (m *PodStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodStatus.Merge(m, src)
}
func (m *PodStatus) XXX_Size() int {
	return xxx_messageInfo_PodStatus.Size(m)
}
func (m *PodStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PodStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PodStatus proto.InternalMessageInfo

func (m *PodStatus) GetPhase() string {
	if m != nil && m.Phase != nil {
		return *m.Phase
	}
	return ""
}

func (m *PodStatus) GetConditions() []*PodCondition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *PodStatus) GetHostIP() string {
	if m != nil && m.HostIP != nil {
		return *m.HostIP
	}
	return ""
}

func (m *PodStatus) GetPodIP() string {
	if m != nil && m.PodIP != nil {
		return *m.PodIP
	}
	return ""
}

func (m *PodStatus) GetPodIPs() []*PodIP {
	if m != nil {
		return m.PodIPs
	}
	return nil
}

func (m *PodStatus) GetStartTime() *v1.Time {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *PodStatus) GetContainerStatuses() []*ContainerStatus {
	if m != nil {
		return m.ContainerStatuses
	}
	return nil
}

func (m *PodStatus) GetQosClass() string {
	if m != nil && m.QosClass != nil {
		return *m.QosClass
	}
	return ""
}

func (m *PortStatus) Reset()         { *m = PortStatus{} }
func (m *PortStatus) String() string { return proto.CompactTextString(m) }
func (*PortStatus) ProtoMessage()    {}
func (*PortStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{27}
}
func (m *PortStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortStatus.Unmarshal(m, b)
}
func (m *PortStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortStatus.Marshal(b, m, deterministic)
}
func (m *PortStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortStatus.Merge(m, src)
}
func (m *PortStatus) XXX_Size() int {
	return xxx_messageInfo_PortStatus.Size(m)
}
func (m *PortStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_PortStatus.DiscardUnknown(m)
}

var xxx_messageInfo_PortStatus proto.InternalMessageInfo

func (m *PortStatus) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *PortStatus) GetProtocol() string {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return ""
}

func (m *PortStatus) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *Secret) Reset()         { *m = Secret{} }
func (m *Secret) String() string { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()    {}
func (*Secret) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{28}
}
func (m *Secret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Secret.Unmarshal(m, b)
}
func (m *Secret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Secret.Marshal(b, m, deterministic)
}
func (m *Secret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Secret.Merge(m, src)
}
func (m *Secret) XXX_Size() int {
	return xxx_messageInfo_Secret.Size(m)
}
func (m *Secret) XXX_DiscardUnknown() {
	xxx_messageInfo_Secret.DiscardUnknown(m)
}

var xxx_messageInfo_Secret proto.InternalMessageInfo

func (m *Secret) GetMetadata() *v1.ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Secret) GetImmutable() bool {
	if m != nil && m.Immutable != nil {
		return *m.Immutable
	}
	return false
}

func (m *Secret) GetData() map[string][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Secret) GetStringData() map[string]string {
	if m != nil {
		return m.StringData
	}
	return nil
}

func (m *Secret) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *SecretList) Reset()         { *m = SecretList{} }
func (m *SecretList) String() string { return proto.CompactTextString(m) }
func (*SecretList) ProtoMessage()    {}
func (*SecretList) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{29}
}
func (m *SecretList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretList.Unmarshal(m, b)
}
func (m *SecretList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretList.Marshal(b, m, deterministic)
}
func (m *SecretList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretList.Merge(m, src)
}
func (m *SecretList) XXX_Size() int {
	return xxx_messageInfo_SecretList.Size(m)
}
func (m *SecretList) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretList.DiscardUnknown(m)
}

var xxx_messageInfo_SecretList proto.InternalMessageInfo

func (m *SecretList) GetMetadata() *v1.ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *SecretList) GetItems() []*Secret {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{30}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetMetadata() *v1.ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Service) GetSpec() *ServiceSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Service) GetStatus() *ServiceStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ServiceList) Reset()         { *m = ServiceList{} }
func (m *ServiceList) String() string { return proto.CompactTextString(m) }
func (*ServiceList) ProtoMessage()    {}
func (*ServiceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{31}
}
func (m *ServiceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceList.Unmarshal(m, b)
}
func (m *ServiceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceList.Marshal(b, m, deterministic)
}
func (m *ServiceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceList.Merge(m, src)
}
func (m *ServiceList) XXX_Size() int {
	return xxx_messageInfo_ServiceList.Size(m)
}
func (m *ServiceList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceList proto.InternalMessageInfo

func (m *ServiceList) GetMetadata() *v1.ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ServiceList) GetItems() []*Service {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ServicePort) Reset()         { *m = ServicePort{} }
func (m *ServicePort) String() string { return proto.CompactTextString(m) }
func (*ServicePort) ProtoMessage()    {}
func (*ServicePort) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{32}
}
func (m *ServicePort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServicePort.Unmarshal(m, b)
}
func (m *ServicePort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServicePort.Marshal(b, m, deterministic)
}
func (m *ServicePort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServicePort.Merge(m, src)
}
func (m *ServicePort) XXX_Size() int {
	return xxx_messageInfo_ServicePort.Size(m)
}
func (m *ServicePort) XXX_DiscardUnknown() {
	xxx_messageInfo_ServicePort.DiscardUnknown(m)
}

var xxx_messageInfo_ServicePort proto.InternalMessageInfo

func (m *ServicePort) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ServicePort) GetProtocol() string {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return ""
}

func (m *ServicePort) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *ServicePort) GetNodePort() int32 {
	if m != nil && m.NodePort != nil {
		return *m.NodePort
	}
	return 0
}

func (m *ServiceSpec) Reset()         { *m = ServiceSpec{} }
func (m *ServiceSpec) String() string { return proto.CompactTextString(m) }
func (*ServiceSpec) ProtoMessage()    {}
func (*ServiceSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{33}
}
func (m *ServiceSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceSpec.Unmarshal(m, b)
}
func (m *ServiceSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceSpec.Marshal(b, m, deterministic)
}
func (m *ServiceSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceSpec.Merge(m, src)
}
func (m *ServiceSpec) XXX_Size() int {
	return xxx_messageInfo_ServiceSpec.Size(m)
}
func (m *ServiceSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceSpec proto.InternalMessageInfo

func (m *ServiceSpec) GetPorts() []*ServicePort {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *ServiceSpec) GetSelector() map[string]string {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *ServiceSpec) GetClusterIP() string {
	if m != nil && m.ClusterIP != nil {
		return *m.ClusterIP
	}
	return ""
}

func (m *ServiceSpec) GetClusterIPs() []string {
	if m != nil {
		return m.ClusterIPs
	}
	return nil
}

func (m *ServiceSpec) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *ServiceSpec) GetExternalIPs() []string {
	if m != nil {
		return m.ExternalIPs
	}
	return nil
}

func (m *ServiceSpec) GetSessionAffinity() string {
	if m != nil && m.SessionAffinity != nil {
		return *m.SessionAffinity
	}
	return ""
}

func (m *ServiceSpec) GetLoadBalancerIP() string {
	if m != nil && m.LoadBalancerIP != nil {
		return *m.LoadBalancerIP
	}
	return ""
}

func (m *ServiceSpec) GetLoadBalancerSourceRanges() []string {
	if m != nil {
		return m.LoadBalancerSourceRanges
	}
	return nil
}

func (m *ServiceSpec) GetExternalTrafficPolicy() string {
	if m != nil && m.ExternalTrafficPolicy != nil {
		return *m.ExternalTrafficPolicy
	}
	return ""
}

func (m *ServiceSpec) GetHealthCheckNodePort() int32 {
	if m != nil && m.HealthCheckNodePort != nil {
		return *m.HealthCheckNodePort
	}
	return 0
}

func (m *ServiceSpec) GetSessionAffinityConfig() *SessionAffinityConfig {
	if m != nil {
		return m.SessionAffinityConfig
	}
	return nil
}

func (m *ServiceSpec) GetIpFamilies() []string {
	if m != nil {
		return m.IpFamilies
	}
	return nil
}

func (m *ServiceSpec) GetIpFamilyPolicy() string {
	if m != nil && m.IpFamilyPolicy != nil {
		return *m.IpFamilyPolicy
	}
	return ""
}

func (m *ServiceSpec) GetLoadBalancerClass() string {
	if m != nil && m.LoadBalancerClass != nil {
		return *m.LoadBalancerClass
	}
	return ""
}

func (m *ServiceSpec) GetInternalTrafficPolicy() string {
	if m != nil && m.InternalTrafficPolicy != nil {
		return *m.InternalTrafficPolicy
	}
	return ""
}

func (m *ServiceStatus) Reset()         { *m = ServiceStatus{} }
func (m *ServiceStatus) String() string { return proto.CompactTextString(m) }
func (*ServiceStatus) ProtoMessage()    {}
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{34}
}
func (m *ServiceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStatus.Unmarshal(m, b)
}
func (m *ServiceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStatus.Marshal(b, m, deterministic)
}
func (m *ServiceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStatus.Merge(m, src)
}
func (m *ServiceStatus) XXX_Size() int {
	return xxx_messageInfo_ServiceStatus.Size(m)
}
func (m *ServiceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStatus proto.InternalMessageInfo

func (m *ServiceStatus) GetLoadBalancer() *LoadBalancerStatus {
	if m != nil {
		return m.LoadBalancer
	}
	return nil
}

func (m *ServiceStatus) GetConditions() []*v1.Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *SessionAffinityConfig) Reset()         { *m = SessionAffinityConfig{} }
func (m *SessionAffinityConfig) String() string { return proto.CompactTextString(m) }
func (*SessionAffinityConfig) ProtoMessage()    {}
func (*SessionAffinityConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{35}
}
func (m *SessionAffinityConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionAffinityConfig.Unmarshal(m, b)
}
func (m *SessionAffinityConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionAffinityConfig.Marshal(b, m, deterministic)
}
func (m *SessionAffinityConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionAffinityConfig.Merge(m, src)
}
func (m *SessionAffinityConfig) XXX_Size() int {
	return xxx_messageInfo_SessionAffinityConfig.Size(m)
}
func (m *SessionAffinityConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionAffinityConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SessionAffinityConfig proto.InternalMessageInfo

func (m *SessionAffinityConfig) GetClientIP() *ClientIPConfig {
	if m != nil {
		return m.ClientIP
	}
	return nil
}

func (m *Taint) Reset()         { *m = Taint{} }
func (m *Taint) String() string { return proto.CompactTextString(m) }
func (*Taint) ProtoMessage()    {}
func (*Taint) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{36}
}
func (m *Taint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Taint.Unmarshal(m, b)
}
func (m *Taint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Taint.Marshal(b, m, deterministic)
}
func (m *Taint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Taint.Merge(m, src)
}
func (m *Taint) XXX_Size() int {
	return xxx_messageInfo_Taint.Size(m)
}
func (m *Taint) XXX_DiscardUnknown() {
	xxx_messageInfo_Taint.DiscardUnknown(m)
}

var xxx_messageInfo_Taint proto.InternalMessageInfo

func (m *Taint) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Taint) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *Taint) GetEffect() string {
	if m != nil && m.Effect != nil {
		return *m.Effect
	}
	return ""
}

func (m *Taint) GetTimeAdded() *v1.Time {
	if m != nil {
		return m.TimeAdded
	}
	return nil
}

func (m *TypedLocalObjectReference) Reset()         { *m = TypedLocalObjectReference{} }
func (m *TypedLocalObjectReference) String() string { return proto.CompactTextString(m) }
func (*TypedLocalObjectReference) ProtoMessage()    {}
func (*TypedLocalObjectReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{37}
}
func (m *TypedLocalObjectReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypedLocalObjectReference.Unmarshal(m, b)
}
func (m *TypedLocalObjectReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypedLocalObjectReference.Marshal(b, m, deterministic)
}
func (m *TypedLocalObjectReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypedLocalObjectReference.Merge(m, src)
}
func (m *TypedLocalObjectReference) XXX_Size() int {
	return xxx_messageInfo_TypedLocalObjectReference.Size(m)
}
func (m *TypedLocalObjectReference) XXX_DiscardUnknown() {
	xxx_messageInfo_TypedLocalObjectReference.DiscardUnknown(m)
}

var xxx_messageInfo_TypedLocalObjectReference proto.InternalMessageInfo

func (m *TypedLocalObjectReference) GetApiGroup() string {
	if m != nil && m.ApiGroup != nil {
		return *m.ApiGroup
	}
	return ""
}

func (m *TypedLocalObjectReference) GetKind() string {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return ""
}

func (m *TypedLocalObjectReference) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *VolumeMount) Reset()         { *m = VolumeMount{} }
func (m *VolumeMount) String() string { return proto.CompactTextString(m) }
func (*VolumeMount) ProtoMessage()    {}
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return fileDescriptor_871504499faea14d, []int{38}
}
func (m *VolumeMount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeMount.Unmarshal(m, b)
}
func (m *VolumeMount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeMount.Marshal(b, m, deterministic)
}
func (m *VolumeMount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeMount.Merge(m, src)
}
func (m *VolumeMount) XXX_Size() int {
	return xxx_messageInfo_VolumeMount.Size(m)
}
func (m *VolumeMount) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeMount.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeMount proto.InternalMessageInfo

func (m *VolumeMount) GetMountPath() string {
	if m != nil && m.MountPath != nil {
		return *m.MountPath
	}
	return ""
}

func init() {
	proto.RegisterType((*ClientIPConfig)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.ClientIPConfig")
	proto.RegisterType((*Container)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.Container")
	proto.RegisterType((*ContainerPort)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.ContainerPort")
	proto.RegisterType((*ContainerState)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.ContainerState")
	proto.RegisterType((*ContainerStateRunning)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.ContainerStateRunning")
	proto.RegisterType((*ContainerStatus)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.ContainerStatus")
	proto.RegisterType((*EndpointAddress)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.EndpointAddress")
	proto.RegisterType((*EndpointPort)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.EndpointPort")
	proto.RegisterType((*EndpointSubset)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.EndpointSubset")
	proto.RegisterType((*Endpoints)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.Endpoints")
	proto.RegisterType((*EndpointsList)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.EndpointsList")
	proto.RegisterType((*LoadBalancerIngress)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.LoadBalancerIngress")
	proto.RegisterType((*LoadBalancerStatus)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.LoadBalancerStatus")
	proto.RegisterType((*Namespace)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.Namespace")
	proto.RegisterType((*NamespaceList)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.NamespaceList")
	proto.RegisterType((*Node)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.Node")
	proto.RegisterType((*NodeAddress)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.NodeAddress")
	proto.RegisterType((*NodeCondition)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.NodeCondition")
	proto.RegisterType((*NodeList)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.NodeList")
	proto.RegisterType((*NodeSpec)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.NodeSpec")
	proto.RegisterType((*NodeStatus)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.NodeStatus")
	proto.RegisterType((*Pod)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.Pod")
	proto.RegisterType((*PodCondition)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.PodCondition")
	proto.RegisterType((*PodIP)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.PodIP")
	proto.RegisterType((*PodList)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.PodList")
	proto.RegisterType((*PodSpec)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.PodSpec")
	proto.RegisterType((*PodStatus)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.PodStatus")
	proto.RegisterType((*PortStatus)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.PortStatus")
	proto.RegisterType((*Secret)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.Secret")
	proto.RegisterMapType((map[string][]byte)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.Secret.DataEntry")
	proto.RegisterMapType((map[string]string)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.Secret.StringDataEntry")
	proto.RegisterType((*SecretList)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.SecretList")
	proto.RegisterType((*Service)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.Service")
	proto.RegisterType((*ServiceList)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.ServiceList")
	proto.RegisterType((*ServicePort)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.ServicePort")
	proto.RegisterType((*ServiceSpec)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.ServiceSpec")
	proto.RegisterMapType((map[string]string)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.ServiceSpec.SelectorEntry")
	proto.RegisterType((*ServiceStatus)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.ServiceStatus")
	proto.RegisterType((*SessionAffinityConfig)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.SessionAffinityConfig")
	proto.RegisterType((*Taint)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.Taint")
	proto.RegisterType((*TypedLocalObjectReference)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.TypedLocalObjectReference")
	proto.RegisterType((*VolumeMount)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.core.v1.VolumeMount")
}

func init() {
	proto.RegisterFile("github.com/cilium/cilium/pkg/k8s/slim/k8s/api/core/v1/generated.proto", fileDescriptor_871504499faea14d)
}

var fileDescriptor_871504499faea14d = []byte{
	// 1952 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x59, 0xcd, 0x8f, 0xdc, 0x48,
	0x15, 0x97, 0xfb, 0x63, 0xba, 0xfb, 0xf5, 0xcc, 0x84, 0x54, 0x32, 0xc1, 0x8c, 0x10, 0x1a, 0x59,
	0x68, 0x15, 0x09, 0xd4, 0xc3, 0x46, 0x2c, 0x1b, 0x25, 0x9b, 0x25, 0xf3, 0x95, 0xd5, 0xa0, 0x24,
	0x34, 0xee, 0x51, 0x60, 0xb3, 0x2b, 0x76, 0x6b, 0xec, 0xea, 0xee, 0xa2, 0x6d, 0x97, 0x71, 0x55,
	0x0f, 0x3b, 0x7b, 0xe4, 0x2f, 0x40, 0x42, 0x42, 0xe2, 0xc4, 0x81, 0x33, 0x17, 0x0e, 0x48, 0x08,
	0x09, 0x84, 0x10, 0x37, 0x2e, 0x48, 0x9c, 0x91, 0xf8, 0x2f, 0xe0, 0x86, 0xea, 0xcb, 0x6d, 0x77,
	0x7a, 0x58, 0x62, 0xcf, 0x8c, 0xb4, 0xa7, 0xf6, 0x7b, 0xee, 0xfa, 0xbd, 0x57, 0xaf, 0xde, 0x67,
	0x19, 0x8e, 0x26, 0x54, 0x4c, 0xe7, 0xa7, 0x83, 0x80, 0xc5, 0xbb, 0x01, 0x8d, 0xe8, 0x3c, 0xff,
	0x49, 0x67, 0x93, 0xdd, 0xd9, 0x7d, 0xbe, 0xcb, 0x23, 0x1a, 0xab, 0x07, 0x9c, 0xd2, 0xdd, 0x80,
	0x65, 0x64, 0xf7, 0xec, 0xcd, 0xdd, 0x09, 0x49, 0x48, 0x86, 0x05, 0x09, 0x07, 0x69, 0xc6, 0x04,
	0x43, 0x6f, 0x2d, 0x60, 0x06, 0x7a, 0xbd, 0xfd, 0x49, 0x67, 0x93, 0xc1, 0xec, 0x3e, 0x1f, 0x48,
	0x18, 0xf5, 0x80, 0x53, 0x3a, 0x90, 0x30, 0x83, 0xb3, 0x37, 0xb7, 0x9f, 0xbc, 0x96, 0x74, 0xbe,
	0x1b, 0x13, 0x81, 0x57, 0x88, 0xdf, 0x96, 0xff, 0x18, 0x50, 0x26, 0xff, 0x14, 0xe3, 0x60, 0x4a,
	0x13, 0x92, 0x9d, 0x2b, 0x88, 0x6c, 0x9e, 0x08, 0x1a, 0x93, 0x57, 0x16, 0x7c, 0xeb, 0xb3, 0x16,
	0xf0, 0x60, 0x4a, 0x62, 0xbc, 0xbc, 0xce, 0xbb, 0x0f, 0x9b, 0x07, 0x11, 0x25, 0x89, 0x38, 0x1e,
	0x1e, 0xb0, 0x64, 0x4c, 0x27, 0xe8, 0x0d, 0xd8, 0x94, 0x0b, 0xd8, 0x5c, 0x8c, 0x48, 0xc0, 0x92,
	0x90, 0xbb, 0xce, 0x8e, 0x73, 0xb7, 0xed, 0x2f, 0x71, 0xbd, 0xff, 0x38, 0xd0, 0x3b, 0x60, 0x89,
	0xc0, 0x52, 0x16, 0x42, 0xd0, 0x4a, 0x70, 0x4c, 0xd4, 0x7f, 0x7b, 0xbe, 0x7a, 0x46, 0xb7, 0xa1,
	0x4d, 0x63, 0x3c, 0x21, 0x6e, 0x43, 0x31, 0x35, 0x81, 0x5e, 0x42, 0x3b, 0x65, 0x99, 0xe0, 0xee,
	0xda, 0x4e, 0xf3, 0x6e, 0xff, 0xde, 0xe1, 0xa0, 0x92, 0xa5, 0x07, 0xb9, 0xe8, 0x21, 0xcb, 0x84,
	0xaf, 0x21, 0xd1, 0x18, 0xd6, 0xcf, 0x58, 0x34, 0x8f, 0xc9, 0x33, 0x36, 0x4f, 0x04, 0x77, 0x7b,
	0x4a, 0xc4, 0x7e, 0x45, 0x11, 0x2f, 0x16, 0x50, 0x7e, 0x09, 0xd7, 0xfb, 0xa5, 0x03, 0x1b, 0x25,
	0x05, 0x56, 0xee, 0x7f, 0x1b, 0xba, 0x53, 0xc6, 0x85, 0x7c, 0xaf, 0x4c, 0xd0, 0xf6, 0x73, 0x1a,
	0x7d, 0x15, 0x36, 0x82, 0x22, 0x80, 0xdb, 0x54, 0x7f, 0x28, 0x33, 0x25, 0x82, 0x3a, 0xa6, 0x80,
	0x45, 0x6e, 0x4b, 0x21, 0xe7, 0x34, 0xba, 0x03, 0x6b, 0x12, 0xed, 0x78, 0xe8, 0xb6, 0xd5, 0x1b,
	0x43, 0x79, 0x9f, 0xc0, 0x66, 0xae, 0xda, 0x48, 0x60, 0x41, 0xd0, 0x18, 0x3a, 0xd9, 0x3c, 0x49,
	0x68, 0x32, 0x51, 0x6a, 0xf4, 0xef, 0x3d, 0xad, 0x6b, 0x73, 0x85, 0xeb, 0x6b, 0x4c, 0xdf, 0x82,
	0x7b, 0x1c, 0xb6, 0x56, 0xfe, 0x03, 0xbd, 0x84, 0x1e, 0x17, 0x38, 0x13, 0x24, 0xdc, 0x13, 0xca,
	0x42, 0xfd, 0x7b, 0xef, 0xbc, 0x9e, 0x0a, 0x7c, 0x20, 0x23, 0x45, 0xea, 0x70, 0x42, 0x63, 0xe2,
	0x2f, 0xe0, 0xbc, 0x9f, 0x39, 0x70, 0xa3, 0x24, 0x75, 0xce, 0xd1, 0x07, 0xd0, 0xe6, 0x52, 0xbe,
	0xd9, 0xee, 0xd1, 0xe5, 0x6c, 0x57, 0x63, 0xa2, 0x1d, 0xe8, 0xe7, 0x87, 0x74, 0x7c, 0xe8, 0x76,
	0x95, 0xf1, 0x8b, 0x2c, 0xef, 0x11, 0xdc, 0x38, 0x4a, 0xc2, 0x94, 0xd1, 0x44, 0xec, 0x85, 0x61,
	0x46, 0x38, 0x47, 0x9b, 0xd0, 0xa0, 0xa9, 0x71, 0x8e, 0x06, 0x4d, 0xe5, 0xc1, 0x26, 0x2c, 0x24,
	0xcf, 0xa5, 0xcb, 0x98, 0x83, 0xb5, 0xb4, 0xe7, 0xc3, 0xba, 0x5d, 0x7e, 0xa1, 0x6b, 0x21, 0x68,
	0xa5, 0x0b, 0xb7, 0x52, 0xcf, 0x25, 0x67, 0x69, 0x96, 0x9d, 0xc5, 0xfb, 0xbb, 0x03, 0x9b, 0x16,
	0x74, 0x34, 0x3f, 0xe5, 0x44, 0xa0, 0x10, 0x7a, 0x58, 0x6b, 0x47, 0x64, 0x88, 0xcb, 0x40, 0x79,
	0x52, 0xd1, 0x50, 0x4b, 0xbb, 0xf5, 0x17, 0xc0, 0xe8, 0x7d, 0x1b, 0xed, 0x4d, 0x25, 0xe1, 0xa0,
	0xa6, 0x84, 0x42, 0xb0, 0x7b, 0x7f, 0x73, 0xa0, 0x67, 0xf9, 0x1c, 0xfd, 0x10, 0xba, 0xd2, 0x45,
	0x42, 0x2c, 0xb0, 0x71, 0xb1, 0xfd, 0xaa, 0x2e, 0xf6, 0xdd, 0xd3, 0x1f, 0x91, 0x40, 0x3c, 0x23,
	0x02, 0xfb, 0x39, 0x26, 0xfa, 0x08, 0x3a, 0x5c, 0x19, 0x8e, 0xbb, 0x0d, 0xb5, 0x95, 0xa3, 0x9a,
	0x5b, 0xd1, 0xc7, 0xe0, 0x5b, 0x54, 0xef, 0xaf, 0x0e, 0x6c, 0xe4, 0xdb, 0x79, 0x4a, 0xb9, 0x40,
	0x1f, 0xbe, 0xb2, 0xa5, 0xc7, 0x55, 0xb7, 0x24, 0xf1, 0x96, 0x36, 0xf4, 0x02, 0xda, 0x54, 0x90,
	0xd8, 0x6e, 0xe7, 0x71, 0xcd, 0xed, 0x70, 0x5f, 0xc3, 0x79, 0xbf, 0x75, 0xe0, 0xd6, 0x53, 0x86,
	0xc3, 0x7d, 0x1c, 0xe1, 0x24, 0x20, 0xd9, 0x71, 0x32, 0xb9, 0x28, 0x04, 0x64, 0xc6, 0x52, 0xae,
	0xad, 0x0b, 0x44, 0x4e, 0xcb, 0xdc, 0x46, 0xd3, 0x67, 0x2c, 0x24, 0xc6, 0x91, 0x0d, 0x85, 0xbe,
	0x6f, 0xbd, 0xa9, 0xa5, 0x74, 0xde, 0xab, 0xa8, 0xb3, 0xf4, 0x22, 0x9d, 0x2a, 0xac, 0x2f, 0x7d,
	0x0a, 0xa8, 0xa8, 0xb3, 0xc9, 0x23, 0x21, 0x74, 0xa8, 0xd6, 0xde, 0x04, 0xc8, 0x77, 0x2a, 0x0a,
	0x5c, 0x61, 0x0f, 0xdf, 0x42, 0x7b, 0x33, 0xe8, 0xc9, 0xb8, 0xe7, 0x29, 0x0e, 0xc8, 0x55, 0xbb,
	0xb1, 0xf2, 0xb2, 0x5c, 0xda, 0xe7, 0xc7, 0xcb, 0x72, 0x95, 0xad, 0x97, 0xfd, 0xa2, 0x01, 0xad,
	0xe7, 0xd2, 0x25, 0xae, 0x3a, 0xee, 0x47, 0xd0, 0xe2, 0x29, 0x09, 0x4c, 0x29, 0xf9, 0x76, 0x55,
	0xfd, 0x59, 0x48, 0x46, 0x29, 0x09, 0x7c, 0x05, 0x86, 0xde, 0x87, 0x35, 0xae, 0x5c, 0x4c, 0xf9,
	0x77, 0x75, 0x47, 0x56, 0xb0, 0xda, 0x91, 0x0d, 0xa0, 0xf7, 0x10, 0xfa, 0x92, 0x6b, 0x0b, 0x0f,
	0x82, 0x96, 0x38, 0x4f, 0xf3, 0xe2, 0x21, 0x9f, 0x91, 0x0b, 0x1d, 0x93, 0xa0, 0x4d, 0xe0, 0x59,
	0xd2, 0x1b, 0xc1, 0x86, 0x5c, 0x7c, 0xc0, 0x92, 0x90, 0x0a, 0xca, 0x92, 0x95, 0xcb, 0xef, 0xe4,
	0xca, 0xeb, 0xd5, 0x86, 0x92, 0xfc, 0x8c, 0x60, 0xce, 0x12, 0xdb, 0x90, 0x68, 0xca, 0xfb, 0x83,
	0x03, 0x5d, 0x89, 0x7a, 0x0d, 0xde, 0xf6, 0xbd, 0xb2, 0xb7, 0x3d, 0xac, 0x61, 0x56, 0xeb, 0x68,
	0xbf, 0x33, 0xda, 0xcb, 0xd3, 0x93, 0x96, 0x4b, 0x59, 0x78, 0x70, 0x7c, 0xe8, 0x1b, 0x8b, 0x58,
	0x52, 0x15, 0x5f, 0xfd, 0xc8, 0xdd, 0xce, 0x4e, 0x53, 0x15, 0x5f, 0x43, 0xa3, 0xaf, 0x00, 0xa4,
	0x19, 0x3b, 0xa3, 0xa1, 0x6a, 0x18, 0x74, 0x46, 0x2b, 0x70, 0xd0, 0x09, 0xac, 0xc9, 0xde, 0x41,
	0x70, 0xb7, 0xad, 0xd4, 0x7e, 0xa7, 0xa2, 0xda, 0x27, 0x12, 0xc4, 0x37, 0x58, 0xde, 0x3f, 0x1c,
	0x80, 0x85, 0x7f, 0xa0, 0x10, 0x20, 0xb0, 0xc7, 0x6a, 0xf3, 0xe7, 0x61, 0x0d, 0xfb, 0xe4, 0x3e,
	0xe2, 0x17, 0x70, 0xd1, 0xc7, 0xc5, 0xa6, 0xa2, 0x5d, 0xab, 0xfb, 0x2e, 0x78, 0x71, 0xa1, 0xa1,
	0xf0, 0x7e, 0xde, 0x80, 0xe6, 0x90, 0x85, 0x57, 0x1e, 0xf7, 0x7e, 0x29, 0xee, 0xdf, 0xad, 0x5c,
	0x69, 0xc2, 0x42, 0xd8, 0xff, 0x60, 0x29, 0xec, 0x1f, 0xd7, 0x40, 0x2d, 0x47, 0xfd, 0x1f, 0x1b,
	0xb0, 0x3e, 0x64, 0x61, 0xb5, 0xc0, 0x3d, 0x85, 0x8d, 0x08, 0x73, 0x31, 0xcc, 0xd8, 0x29, 0x91,
	0xed, 0xb5, 0xd1, 0xae, 0x5e, 0x8b, 0x5e, 0x86, 0x44, 0x11, 0x20, 0xc9, 0x38, 0xc9, 0x70, 0xc2,
	0x95, 0x86, 0x4a, 0x50, 0xeb, 0x12, 0x04, 0xad, 0xc0, 0xbd, 0x28, 0x15, 0xc9, 0xf8, 0x8d, 0x09,
	0xe7, 0x72, 0x26, 0x5d, 0xd3, 0xf1, 0x6b, 0x48, 0xef, 0x8b, 0xd0, 0x1e, 0xb2, 0xf0, 0x78, 0xb8,
	0xdc, 0xa6, 0x78, 0xbf, 0x77, 0xa0, 0x33, 0x64, 0xe1, 0x35, 0x24, 0xaf, 0x61, 0x39, 0x79, 0x3d,
	0xa8, 0xee, 0x1c, 0x36, 0x77, 0xfd, 0xa5, 0xa1, 0x74, 0x57, 0xa9, 0x6b, 0x0a, 0x9b, 0x34, 0xa1,
	0x22, 0x9f, 0x69, 0xb8, 0x7b, 0xbb, 0x56, 0x45, 0xce, 0x81, 0xfc, 0x25, 0x5c, 0xf4, 0xb1, 0xca,
	0x34, 0x56, 0x4a, 0xe3, 0x92, 0xa4, 0x14, 0x30, 0xd1, 0x00, 0x10, 0x27, 0xd9, 0x19, 0x0d, 0xc8,
	0x5e, 0x10, 0xc8, 0x89, 0x5c, 0xcd, 0x51, 0x7a, 0x12, 0x5b, 0xf1, 0xa6, 0x34, 0x6d, 0x41, 0x79,
	0xda, 0x92, 0xe3, 0x9c, 0x6c, 0x3b, 0x9f, 0x13, 0xf1, 0x13, 0x96, 0xcd, 0xdc, 0xfe, 0x8e, 0x73,
	0xb7, 0xeb, 0x17, 0x59, 0xde, 0xbf, 0x9b, 0xd0, 0xcb, 0x23, 0x0e, 0xdd, 0x86, 0x76, 0x3a, 0xc5,
	0xdc, 0x46, 0x96, 0x26, 0x50, 0x50, 0xca, 0xae, 0x8d, 0x5a, 0xb3, 0x4e, 0x31, 0x8e, 0x4b, 0xc9,
	0xf5, 0x82, 0x89, 0x5f, 0xa9, 0x24, 0x7d, 0xd7, 0xf8, 0xb4, 0x26, 0x64, 0x55, 0x51, 0x0f, 0xdc,
	0x5d, 0xaf, 0x55, 0x55, 0x54, 0x58, 0xf8, 0x06, 0x2b, 0x1f, 0xe5, 0x55, 0xf8, 0x76, 0x2e, 0x6d,
	0x94, 0x57, 0x51, 0x2b, 0xe0, 0x66, 0x50, 0x9e, 0xe4, 0x09, 0x77, 0xbb, 0xb5, 0x26, 0xd3, 0xa5,
	0x9b, 0x01, 0xff, 0x55, 0x01, 0xd2, 0x39, 0x7e, 0xcc, 0xf8, 0x41, 0x84, 0x39, 0x77, 0x7b, 0xda,
	0x39, 0x2c, 0xed, 0xf9, 0x00, 0x8b, 0x59, 0x21, 0x1f, 0xba, 0x9d, 0x0b, 0x86, 0xee, 0xc6, 0xd2,
	0x0d, 0xcd, 0x6d, 0x68, 0x93, 0x2c, 0x63, 0x99, 0x29, 0xf9, 0x9a, 0xf0, 0xfe, 0xd9, 0x84, 0xb5,
	0x11, 0x09, 0x32, 0x22, 0xae, 0xbc, 0x86, 0x7d, 0x19, 0x7a, 0x34, 0x8e, 0xe7, 0x02, 0x9f, 0x46,
	0x44, 0xf9, 0x4c, 0xd7, 0x5f, 0x30, 0xd0, 0x07, 0xd0, 0x52, 0x92, 0xb5, 0xb7, 0xbe, 0x57, 0xd1,
	0xc2, 0x7a, 0x2b, 0x83, 0x43, 0x2c, 0xf0, 0x51, 0x22, 0xb2, 0x73, 0x5f, 0x81, 0xa2, 0x18, 0x80,
	0x8b, 0x8c, 0x26, 0x13, 0xf9, 0xc2, 0xb4, 0x1b, 0xcf, 0xea, 0x89, 0x18, 0xe5, 0x78, 0x5a, 0x50,
	0x41, 0x40, 0x5e, 0xee, 0x9a, 0x8b, 0x72, 0xb7, 0xfd, 0x36, 0xf4, 0xf2, 0x3f, 0xa3, 0x2f, 0x40,
	0x73, 0x46, 0xce, 0x4d, 0xd0, 0xca, 0x47, 0x79, 0x3a, 0x67, 0x38, 0x9a, 0xeb, 0xe1, 0x73, 0xdd,
	0xd7, 0xc4, 0x83, 0xc6, 0x7d, 0x67, 0xfb, 0x11, 0xdc, 0x58, 0x92, 0xf5, 0x59, 0xcb, 0x7b, 0x85,
	0xe5, 0xde, 0x9f, 0x1c, 0x00, 0xad, 0xf2, 0x35, 0x14, 0x8d, 0x51, 0xb9, 0x68, 0x3c, 0xaa, 0x65,
	0x62, 0x5b, 0x37, 0x7e, 0xd5, 0x80, 0xce, 0x48, 0xa7, 0xd1, 0x2b, 0xf7, 0xd1, 0x17, 0xa5, 0x3e,
	0x6b, 0xbf, 0xb2, 0xfe, 0x4a, 0xdb, 0x42, 0xaf, 0xf5, 0xe1, 0x52, 0xaf, 0x75, 0x58, 0x13, 0xb9,
	0xdc, 0x6f, 0xfd, 0xd9, 0x81, 0xbe, 0x79, 0x73, 0x0d, 0x87, 0x7c, 0x52, 0x3e, 0xe4, 0x77, 0xeb,
	0x6d, 0xc5, 0x9e, 0x72, 0x9c, 0x6f, 0xe1, 0x7f, 0xdd, 0x60, 0x5f, 0x98, 0xdd, 0x6c, 0x36, 0x6c,
	0x96, 0xb3, 0xa1, 0x2c, 0xac, 0xea, 0x42, 0xbb, 0xad, 0x6f, 0xbc, 0x2d, 0xed, 0xfd, 0xa6, 0x93,
	0xcb, 0x1b, 0xe9, 0x66, 0xd8, 0xdc, 0xe5, 0x38, 0xb5, 0xc6, 0x84, 0xc2, 0x16, 0xec, 0x57, 0x80,
	0x08, 0xba, 0x9c, 0x44, 0x24, 0x10, 0x2c, 0x33, 0x16, 0x1b, 0xd6, 0x77, 0xab, 0xc1, 0xc8, 0x40,
	0xea, 0xe4, 0x93, 0x4b, 0x90, 0x49, 0x36, 0x88, 0xe6, 0x5c, 0x90, 0xec, 0x78, 0x68, 0xf2, 0xcf,
	0x82, 0x21, 0x67, 0xbf, 0x9c, 0xe0, 0x2e, 0x52, 0x93, 0x61, 0x81, 0x93, 0x27, 0xae, 0x56, 0xa1,
	0x4f, 0xdf, 0x81, 0x3e, 0xf9, 0x44, 0x90, 0x2c, 0xc1, 0x91, 0x5c, 0xd4, 0x56, 0x8b, 0x8a, 0x2c,
	0x74, 0x17, 0x6e, 0x70, 0xc2, 0x39, 0x65, 0xc9, 0xde, 0x78, 0x2c, 0xdb, 0xaf, 0x73, 0x55, 0x8b,
	0x7b, 0xfe, 0x32, 0x1b, 0xbd, 0x01, 0x9b, 0x51, 0xf1, 0xf2, 0x69, 0x68, 0xda, 0xa4, 0x25, 0x2e,
	0x7a, 0x00, 0x6e, 0x91, 0x33, 0x62, 0xf3, 0x2c, 0x20, 0x3e, 0x4e, 0x26, 0x44, 0x7f, 0x45, 0xe9,
	0xf9, 0x17, 0xbe, 0x47, 0xdf, 0x84, 0x2d, 0xab, 0xdc, 0x49, 0x86, 0xc7, 0x63, 0x1a, 0x0c, 0x59,
	0x44, 0x83, 0x73, 0xd5, 0x4c, 0xf5, 0xfc, 0xd5, 0x2f, 0xd1, 0x37, 0xe0, 0xd6, 0x94, 0xe0, 0x48,
	0x4c, 0x0f, 0xa6, 0x24, 0x98, 0x3d, 0xb7, 0x6e, 0xb3, 0xae, 0xdc, 0x66, 0xd5, 0x2b, 0xf4, 0x53,
	0x07, 0xb6, 0x96, 0xf6, 0xa7, 0xbf, 0x59, 0xb9, 0x9b, 0xb5, 0x3e, 0x6b, 0x8c, 0x56, 0x61, 0xfa,
	0xab, 0x45, 0xc9, 0x03, 0xa5, 0xe9, 0x13, 0x1c, 0xd3, 0x88, 0x12, 0xee, 0xde, 0xd2, 0x07, 0xba,
	0xe0, 0x48, 0x83, 0x1b, 0xea, 0xdc, 0x58, 0xe1, 0xa6, 0x36, 0x78, 0x99, 0x8b, 0xbe, 0x0e, 0x37,
	0x8b, 0x06, 0xd5, 0xfd, 0xc7, 0x96, 0xfa, 0xeb, 0xab, 0x2f, 0xa4, 0x89, 0x69, 0xb2, 0xca, 0xc4,
	0x77, 0xb4, 0x89, 0x57, 0xbe, 0xdc, 0x7e, 0x08, 0x1b, 0x25, 0xaf, 0x7d, 0xad, 0x32, 0xf6, 0x2f,
	0x47, 0xae, 0x2e, 0x24, 0x3f, 0x14, 0xc3, 0x7a, 0x51, 0x33, 0x93, 0xe8, 0x8e, 0x2f, 0xe1, 0x4e,
	0xd4, 0x64, 0xd7, 0x12, 0x3c, 0xc2, 0x2b, 0x7a, 0xea, 0xbd, 0xaa, 0x59, 0x75, 0x65, 0x47, 0xed,
	0x7d, 0x0a, 0x5b, 0x2b, 0x0f, 0x1f, 0x61, 0xe8, 0x06, 0xe6, 0xb3, 0xa8, 0xd9, 0x66, 0xe5, 0x8f,
	0x48, 0xa5, 0xaf, 0xab, 0x7e, 0x0e, 0xeb, 0xfd, 0xda, 0x81, 0xb6, 0xba, 0xb1, 0xf9, 0x7f, 0x4f,
	0x45, 0xf6, 0xff, 0x64, 0x3c, 0x26, 0x81, 0xb0, 0xb7, 0xe2, 0x9a, 0x92, 0x3d, 0xb9, 0xa0, 0x31,
	0xd9, 0x0b, 0x43, 0x12, 0x5e, 0xca, 0x48, 0xbd, 0x80, 0xf3, 0x3e, 0x82, 0x2f, 0x9d, 0x9c, 0xa7,
	0x24, 0x7c, 0xca, 0x02, 0x1c, 0xe9, 0x02, 0xee, 0x93, 0x31, 0xc9, 0x48, 0x12, 0xa8, 0xf2, 0x80,
	0x53, 0xfa, 0x5e, 0xc6, 0xe6, 0x76, 0x62, 0xce, 0x69, 0x99, 0xd8, 0x66, 0x34, 0x09, 0xcd, 0x0e,
	0xd4, 0x73, 0x5e, 0x62, 0x9a, 0x8b, 0x12, 0xe3, 0x7d, 0x0d, 0xfa, 0x85, 0xef, 0xac, 0x32, 0x9b,
	0xc6, 0xf2, 0x61, 0x88, 0xc5, 0xd4, 0x66, 0xd3, 0x9c, 0xb1, 0xff, 0xf6, 0xcb, 0xb7, 0x2a, 0x7d,
	0xde, 0xff, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x13, 0xb5, 0xee, 0x20, 0x16, 0x20, 0x00, 0x00,
}
