// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/meta/v1/generated.proto

package v1

import (
	fmt "fmt"

	proto "github.com/gogo/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f89ca41f751b36, []int{0}
}
func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (m *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(m, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Condition) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *Condition) GetObservedGeneration() int64 {
	if m != nil && m.ObservedGeneration != nil {
		return *m.ObservedGeneration
	}
	return 0
}

func (m *Condition) GetLastTransitionTime() *Time {
	if m != nil {
		return m.LastTransitionTime
	}
	return nil
}

func (m *Condition) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

func (m *Condition) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *LabelSelector) Reset()         { *m = LabelSelector{} }
func (m *LabelSelector) String() string { return proto.CompactTextString(m) }
func (*LabelSelector) ProtoMessage()    {}
func (*LabelSelector) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f89ca41f751b36, []int{1}
}
func (m *LabelSelector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelSelector.Unmarshal(m, b)
}
func (m *LabelSelector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelSelector.Marshal(b, m, deterministic)
}
func (m *LabelSelector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelSelector.Merge(m, src)
}
func (m *LabelSelector) XXX_Size() int {
	return xxx_messageInfo_LabelSelector.Size(m)
}
func (m *LabelSelector) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelSelector.DiscardUnknown(m)
}

var xxx_messageInfo_LabelSelector proto.InternalMessageInfo

func (m *LabelSelector) GetMatchLabels() map[string]string {
	if m != nil {
		return m.MatchLabels
	}
	return nil
}

func (m *LabelSelector) GetMatchExpressions() []*LabelSelectorRequirement {
	if m != nil {
		return m.MatchExpressions
	}
	return nil
}

func (m *LabelSelectorRequirement) Reset()         { *m = LabelSelectorRequirement{} }
func (m *LabelSelectorRequirement) String() string { return proto.CompactTextString(m) }
func (*LabelSelectorRequirement) ProtoMessage()    {}
func (*LabelSelectorRequirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f89ca41f751b36, []int{2}
}
func (m *LabelSelectorRequirement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelSelectorRequirement.Unmarshal(m, b)
}
func (m *LabelSelectorRequirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelSelectorRequirement.Marshal(b, m, deterministic)
}
func (m *LabelSelectorRequirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelSelectorRequirement.Merge(m, src)
}
func (m *LabelSelectorRequirement) XXX_Size() int {
	return xxx_messageInfo_LabelSelectorRequirement.Size(m)
}
func (m *LabelSelectorRequirement) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelSelectorRequirement.DiscardUnknown(m)
}

var xxx_messageInfo_LabelSelectorRequirement proto.InternalMessageInfo

func (m *LabelSelectorRequirement) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *LabelSelectorRequirement) GetOperator() string {
	if m != nil && m.Operator != nil {
		return *m.Operator
	}
	return ""
}

func (m *LabelSelectorRequirement) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ListMeta) Reset()         { *m = ListMeta{} }
func (m *ListMeta) String() string { return proto.CompactTextString(m) }
func (*ListMeta) ProtoMessage()    {}
func (*ListMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f89ca41f751b36, []int{3}
}
func (m *ListMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMeta.Unmarshal(m, b)
}
func (m *ListMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMeta.Marshal(b, m, deterministic)
}
func (m *ListMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMeta.Merge(m, src)
}
func (m *ListMeta) XXX_Size() int {
	return xxx_messageInfo_ListMeta.Size(m)
}
func (m *ListMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ListMeta proto.InternalMessageInfo

func (m *ListMeta) GetResourceVersion() string {
	if m != nil && m.ResourceVersion != nil {
		return *m.ResourceVersion
	}
	return ""
}

func (m *ListMeta) GetContinue() string {
	if m != nil && m.Continue != nil {
		return *m.Continue
	}
	return ""
}

func (m *ListMeta) GetRemainingItemCount() int64 {
	if m != nil && m.RemainingItemCount != nil {
		return *m.RemainingItemCount
	}
	return 0
}

func (m *ObjectMeta) Reset()         { *m = ObjectMeta{} }
func (m *ObjectMeta) String() string { return proto.CompactTextString(m) }
func (*ObjectMeta) ProtoMessage()    {}
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f89ca41f751b36, []int{4}
}
func (m *ObjectMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectMeta.Unmarshal(m, b)
}
func (m *ObjectMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectMeta.Marshal(b, m, deterministic)
}
func (m *ObjectMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectMeta.Merge(m, src)
}
func (m *ObjectMeta) XXX_Size() int {
	return xxx_messageInfo_ObjectMeta.Size(m)
}
func (m *ObjectMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectMeta proto.InternalMessageInfo

func (m *ObjectMeta) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ObjectMeta) GetGenerateName() string {
	if m != nil && m.GenerateName != nil {
		return *m.GenerateName
	}
	return ""
}

func (m *ObjectMeta) GetNamespace() string {
	if m != nil && m.Namespace != nil {
		return *m.Namespace
	}
	return ""
}

func (m *ObjectMeta) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *ObjectMeta) GetResourceVersion() string {
	if m != nil && m.ResourceVersion != nil {
		return *m.ResourceVersion
	}
	return ""
}

func (m *ObjectMeta) GetGeneration() int64 {
	if m != nil && m.Generation != nil {
		return *m.Generation
	}
	return 0
}

func (m *ObjectMeta) GetDeletionTimestamp() *Time {
	if m != nil {
		return m.DeletionTimestamp
	}
	return nil
}

func (m *ObjectMeta) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ObjectMeta) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *ObjectMeta) GetOwnerReferences() []*OwnerReference {
	if m != nil {
		return m.OwnerReferences
	}
	return nil
}

func (m *OwnerReference) Reset()         { *m = OwnerReference{} }
func (m *OwnerReference) String() string { return proto.CompactTextString(m) }
func (*OwnerReference) ProtoMessage()    {}
func (*OwnerReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f89ca41f751b36, []int{5}
}
func (m *OwnerReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnerReference.Unmarshal(m, b)
}
func (m *OwnerReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnerReference.Marshal(b, m, deterministic)
}
func (m *OwnerReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerReference.Merge(m, src)
}
func (m *OwnerReference) XXX_Size() int {
	return xxx_messageInfo_OwnerReference.Size(m)
}
func (m *OwnerReference) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerReference.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerReference proto.InternalMessageInfo

func (m *OwnerReference) GetApiVersion() string {
	if m != nil && m.ApiVersion != nil {
		return *m.ApiVersion
	}
	return ""
}

func (m *OwnerReference) GetKind() string {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return ""
}

func (m *OwnerReference) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *OwnerReference) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *OwnerReference) GetController() bool {
	if m != nil && m.Controller != nil {
		return *m.Controller
	}
	return false
}

func (m *PartialObjectMetadata) Reset()         { *m = PartialObjectMetadata{} }
func (m *PartialObjectMetadata) String() string { return proto.CompactTextString(m) }
func (*PartialObjectMetadata) ProtoMessage()    {}
func (*PartialObjectMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f89ca41f751b36, []int{6}
}
func (m *PartialObjectMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartialObjectMetadata.Unmarshal(m, b)
}
func (m *PartialObjectMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartialObjectMetadata.Marshal(b, m, deterministic)
}
func (m *PartialObjectMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartialObjectMetadata.Merge(m, src)
}
func (m *PartialObjectMetadata) XXX_Size() int {
	return xxx_messageInfo_PartialObjectMetadata.Size(m)
}
func (m *PartialObjectMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_PartialObjectMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_PartialObjectMetadata proto.InternalMessageInfo

func (m *PartialObjectMetadata) GetMetadata() *ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *PartialObjectMetadataList) Reset()         { *m = PartialObjectMetadataList{} }
func (m *PartialObjectMetadataList) String() string { return proto.CompactTextString(m) }
func (*PartialObjectMetadataList) ProtoMessage()    {}
func (*PartialObjectMetadataList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f89ca41f751b36, []int{7}
}
func (m *PartialObjectMetadataList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartialObjectMetadataList.Unmarshal(m, b)
}
func (m *PartialObjectMetadataList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartialObjectMetadataList.Marshal(b, m, deterministic)
}
func (m *PartialObjectMetadataList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartialObjectMetadataList.Merge(m, src)
}
func (m *PartialObjectMetadataList) XXX_Size() int {
	return xxx_messageInfo_PartialObjectMetadataList.Size(m)
}
func (m *PartialObjectMetadataList) XXX_DiscardUnknown() {
	xxx_messageInfo_PartialObjectMetadataList.DiscardUnknown(m)
}

var xxx_messageInfo_PartialObjectMetadataList proto.InternalMessageInfo

func (m *PartialObjectMetadataList) GetMetadata() *ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *PartialObjectMetadataList) GetItems() []*PartialObjectMetadata {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f89ca41f751b36, []int{8}
}
func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (m *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(m, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetSeconds() int64 {
	if m != nil && m.Seconds != nil {
		return *m.Seconds
	}
	return 0
}

func (m *Time) GetNanos() int32 {
	if m != nil && m.Nanos != nil {
		return *m.Nanos
	}
	return 0
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f89ca41f751b36, []int{9}
}
func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetSeconds() int64 {
	if m != nil && m.Seconds != nil {
		return *m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int32 {
	if m != nil && m.Nanos != nil {
		return *m.Nanos
	}
	return 0
}

func (m *TypeMeta) Reset()         { *m = TypeMeta{} }
func (m *TypeMeta) String() string { return proto.CompactTextString(m) }
func (*TypeMeta) ProtoMessage()    {}
func (*TypeMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f89ca41f751b36, []int{10}
}
func (m *TypeMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeMeta.Unmarshal(m, b)
}
func (m *TypeMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeMeta.Marshal(b, m, deterministic)
}
func (m *TypeMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeMeta.Merge(m, src)
}
func (m *TypeMeta) XXX_Size() int {
	return xxx_messageInfo_TypeMeta.Size(m)
}
func (m *TypeMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TypeMeta proto.InternalMessageInfo

func (m *TypeMeta) GetKind() string {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return ""
}

func (m *TypeMeta) GetApiVersion() string {
	if m != nil && m.ApiVersion != nil {
		return *m.ApiVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*Condition)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.meta.v1.Condition")
	proto.RegisterType((*LabelSelector)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.meta.v1.LabelSelector")
	proto.RegisterMapType((map[string]string)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.meta.v1.LabelSelector.MatchLabelsEntry")
	proto.RegisterType((*LabelSelectorRequirement)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.meta.v1.LabelSelectorRequirement")
	proto.RegisterType((*ListMeta)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.meta.v1.ListMeta")
	proto.RegisterType((*ObjectMeta)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.meta.v1.ObjectMeta")
	proto.RegisterMapType((map[string]string)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.meta.v1.ObjectMeta.AnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.meta.v1.ObjectMeta.LabelsEntry")
	proto.RegisterType((*OwnerReference)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.meta.v1.OwnerReference")
	proto.RegisterType((*PartialObjectMetadata)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.meta.v1.PartialObjectMetadata")
	proto.RegisterType((*PartialObjectMetadataList)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.meta.v1.PartialObjectMetadataList")
	proto.RegisterType((*Time)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.meta.v1.Time")
	proto.RegisterType((*Timestamp)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.meta.v1.Timestamp")
	proto.RegisterType((*TypeMeta)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.meta.v1.TypeMeta")
}

func init() {
	proto.RegisterFile("github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/meta/v1/generated.proto", fileDescriptor_e0f89ca41f751b36)
}

var fileDescriptor_e0f89ca41f751b36 = []byte{
	// 837 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4d, 0x8f, 0xdb, 0x36,
	0x10, 0x85, 0x2c, 0x7b, 0xd7, 0x1e, 0x27, 0xcd, 0x96, 0x68, 0x0b, 0xd5, 0x28, 0x02, 0x43, 0x27,
	0x9f, 0x64, 0x64, 0x0f, 0x8b, 0xed, 0x07, 0x82, 0x36, 0x41, 0x52, 0x14, 0xc8, 0xa6, 0x81, 0xb2,
	0xc8, 0xa1, 0x28, 0x8a, 0x72, 0xa5, 0x89, 0xcd, 0x58, 0x24, 0x55, 0x92, 0x72, 0x62, 0xa0, 0x87,
	0xde, 0x0a, 0xf4, 0x8f, 0xf5, 0x5f, 0xf4, 0x67, 0xf4, 0x5c, 0x90, 0x92, 0x2c, 0x7f, 0xa8, 0x28,
	0xa2, 0xee, 0xc9, 0x33, 0x43, 0xeb, 0xbd, 0x19, 0xf2, 0x3d, 0x4a, 0xf0, 0x74, 0xc1, 0xcc, 0xb2,
	0xb8, 0x89, 0x12, 0xc9, 0xe7, 0x09, 0xcb, 0x58, 0xb1, 0xfd, 0xc9, 0x57, 0x8b, 0xf9, 0xea, 0x52,
	0xcf, 0x75, 0xc6, 0xb8, 0x0b, 0x68, 0xce, 0xf4, 0x9c, 0xa3, 0xa1, 0xf3, 0xf5, 0x83, 0xf9, 0x02,
	0x05, 0x2a, 0x6a, 0x30, 0x8d, 0x72, 0x25, 0x8d, 0x24, 0x17, 0x0d, 0x4e, 0x54, 0x02, 0xd4, 0x3f,
	0xf9, 0x6a, 0x11, 0xad, 0x2e, 0x75, 0x64, 0x71, 0x5c, 0x60, 0x71, 0x22, 0x8b, 0x13, 0xad, 0x1f,
	0x4c, 0x2c, 0x72, 0xc4, 0xa4, 0x05, 0xe7, 0x34, 0x59, 0x32, 0x81, 0x6a, 0xe3, 0xa8, 0x55, 0x21,
	0x0c, 0xe3, 0x78, 0x48, 0x34, 0xb9, 0xf8, 0xaf, 0x07, 0x74, 0xb2, 0x44, 0x4e, 0x0f, 0x9f, 0x0b,
	0x7f, 0xef, 0xc1, 0xe8, 0xb1, 0x14, 0x29, 0x33, 0x4c, 0x0a, 0x42, 0xa0, 0x6f, 0x36, 0x39, 0x06,
	0xde, 0xd4, 0x9b, 0x8d, 0x62, 0x17, 0x93, 0x4f, 0xe0, 0x44, 0x1b, 0x6a, 0x0a, 0x1d, 0xf4, 0x5c,
	0xb5, 0xca, 0x48, 0x04, 0x44, 0xde, 0x68, 0x54, 0x6b, 0x4c, 0xbf, 0x2d, 0x41, 0x99, 0x14, 0x81,
	0x3f, 0xf5, 0x66, 0x7e, 0xdc, 0xb2, 0x42, 0x32, 0x20, 0x19, 0xd5, 0xe6, 0x5a, 0x51, 0xa1, 0x1d,
	0xdb, 0x35, 0xe3, 0x18, 0xf4, 0xa7, 0xde, 0x6c, 0x7c, 0xfe, 0x55, 0xd4, 0x6d, 0x9f, 0x22, 0x8b,
	0x11, 0xb7, 0xe0, 0xda, 0xae, 0x15, 0x52, 0x2d, 0x45, 0x30, 0x28, 0xbb, 0x2e, 0x33, 0x12, 0xc0,
	0x29, 0x47, 0xad, 0xe9, 0x02, 0x83, 0x13, 0xb7, 0x50, 0xa7, 0xe1, 0x9f, 0x3d, 0xb8, 0xfb, 0x8c,
	0xde, 0x60, 0xf6, 0x12, 0x33, 0x4c, 0x8c, 0x54, 0xe4, 0x1d, 0x8c, 0x39, 0x35, 0xc9, 0xd2, 0x55,
	0x75, 0xe0, 0x4d, 0xfd, 0xd9, 0xf8, 0xfc, 0x55, 0xd7, 0x56, 0xf7, 0xb0, 0xa3, 0xab, 0x06, 0xf8,
	0x89, 0x30, 0x6a, 0x13, 0xef, 0x52, 0x91, 0x5f, 0xe1, 0xcc, 0xa5, 0x4f, 0xde, 0xe5, 0x0a, 0xb5,
	0x66, 0x52, 0xd8, 0xdd, 0xb7, 0xf4, 0x2f, 0x6e, 0x85, 0x3e, 0xc6, 0x5f, 0x0a, 0xa6, 0x90, 0xa3,
	0x30, 0xf1, 0x11, 0xd3, 0xe4, 0x21, 0x9c, 0x1d, 0xb6, 0x47, 0xce, 0xc0, 0x5f, 0xe1, 0xa6, 0x12,
	0x86, 0x0d, 0xc9, 0x47, 0x30, 0x58, 0xd3, 0xac, 0xc0, 0x4a, 0x16, 0x65, 0xf2, 0x45, 0xef, 0xd2,
	0x0b, 0x7f, 0x86, 0xe0, 0xdf, 0xd8, 0x5a, 0x70, 0x26, 0x30, 0x94, 0xb9, 0x15, 0x89, 0x54, 0x15,
	0xd4, 0x36, 0xb7, 0xa7, 0xe8, 0x60, 0x75, 0xe0, 0x4f, 0x7d, 0x7b, 0x8a, 0x65, 0x16, 0xfe, 0xe6,
	0xc1, 0xf0, 0x19, 0xd3, 0xe6, 0x0a, 0x0d, 0x25, 0x33, 0xb8, 0xa7, 0x50, 0xcb, 0x42, 0x25, 0xf8,
	0x0a, 0x95, 0x1d, 0xa1, 0xc2, 0x39, 0x2c, 0x5b, 0xaa, 0x44, 0x0a, 0xc3, 0x44, 0x81, 0x4e, 0xa8,
	0xa3, 0x78, 0x9b, 0x5b, 0x39, 0x2b, 0xe4, 0x94, 0x09, 0x26, 0x16, 0xdf, 0x19, 0xe4, 0x8f, 0x65,
	0x21, 0x8c, 0x93, 0xa7, 0x1f, 0xb7, 0xac, 0x84, 0x7f, 0x0f, 0x00, 0xbe, 0xbf, 0x79, 0x83, 0x49,
	0xd9, 0x04, 0x81, 0xbe, 0xa0, 0x7c, 0xeb, 0x1c, 0x1b, 0x93, 0x10, 0xee, 0xd4, 0x76, 0x7b, 0x6e,
	0xd7, 0xca, 0xae, 0xf6, 0x6a, 0xe4, 0x33, 0x18, 0xd9, 0xff, 0xea, 0x9c, 0x26, 0x75, 0x4f, 0x4d,
	0xc1, 0xee, 0x56, 0xc1, 0xd2, 0x4a, 0xc2, 0x36, 0x6c, 0x1b, 0xf6, 0xa4, 0x7d, 0xd8, 0xfb, 0x00,
	0x8b, 0xc6, 0x97, 0xa7, 0x6e, 0x90, 0x9d, 0x0a, 0x79, 0x03, 0x1f, 0xa6, 0x98, 0x61, 0xed, 0x18,
	0x6d, 0x28, 0xcf, 0x83, 0xd1, 0x2d, 0xd8, 0xf1, 0x18, 0x96, 0xbc, 0x86, 0x93, 0xac, 0x34, 0xd1,
	0xd8, 0xa9, 0xf8, 0x79, 0x57, 0x82, 0x66, 0xc7, 0xa3, 0x5d, 0xf3, 0x54, 0xe8, 0xa4, 0x80, 0x31,
	0x15, 0x42, 0x1a, 0x37, 0xa1, 0x0e, 0xee, 0x38, 0xb2, 0x97, 0xb7, 0x40, 0xf6, 0x4d, 0x83, 0x5a,
	0xd9, 0x75, 0x87, 0x87, 0xe4, 0x70, 0x4f, 0xbe, 0x15, 0xa8, 0x62, 0x7c, 0x8d, 0x0a, 0x45, 0x82,
	0x3a, 0xb8, 0xeb, 0xa8, 0x9f, 0x76, 0xa6, 0xde, 0x83, 0x8b, 0x0f, 0xe1, 0x27, 0x9f, 0xc3, 0xb8,
	0xa3, 0x3b, 0xad, 0xbb, 0x0f, 0xa7, 0x79, 0x2f, 0x77, 0xff, 0xe1, 0xc1, 0x07, 0xfb, 0xed, 0x59,
	0xa9, 0xd1, 0x9c, 0xd5, 0x7a, 0x2c, 0xd5, 0xba, 0x53, 0xb1, 0xe6, 0x58, 0x31, 0x91, 0xd6, 0xe6,
	0xb0, 0xf1, 0xd6, 0x30, 0xfe, 0x8e, 0x61, 0x2a, 0xb9, 0xf7, 0x1b, 0xb9, 0xdf, 0x07, 0xb0, 0x0e,
	0x55, 0x32, 0xcb, 0x50, 0x39, 0xa5, 0x0f, 0xe3, 0x9d, 0x4a, 0xf8, 0x16, 0x3e, 0x7e, 0x41, 0x95,
	0x61, 0x34, 0x6b, 0x0e, 0x2b, 0xa5, 0x86, 0x92, 0x9f, 0x60, 0xc8, 0xab, 0xd8, 0xd1, 0x8e, 0xcf,
	0x1f, 0xfd, 0x7f, 0x19, 0xc4, 0x5b, 0xcc, 0xf0, 0x2f, 0x0f, 0x3e, 0x6d, 0x65, 0xb6, 0xd7, 0x12,
	0xf9, 0xf1, 0x88, 0xfd, 0xeb, 0xce, 0xf7, 0x76, 0x75, 0xcd, 0x35, 0xdc, 0x24, 0x81, 0x01, 0x33,
	0xc8, 0xeb, 0x57, 0xc2, 0x55, 0x57, 0xe8, 0xd6, 0xfe, 0xe3, 0x12, 0x3b, 0xbc, 0x80, 0xbe, 0x7b,
	0x91, 0x06, 0x70, 0xaa, 0x31, 0x91, 0x22, 0xd5, 0x6e, 0x12, 0x3f, 0xae, 0x53, 0x2b, 0x11, 0x41,
	0x85, 0x2c, 0xbf, 0x0b, 0x06, 0x71, 0x99, 0x84, 0x5f, 0xc2, 0xa8, 0xf1, 0xfd, 0xfb, 0x3e, 0xfc,
	0x10, 0x86, 0xd7, 0x9b, 0x1c, 0xeb, 0x1b, 0xf5, 0x48, 0x34, 0xfb, 0x42, 0xeb, 0x1d, 0x0a, 0xed,
	0xd1, 0xe5, 0x0f, 0x17, 0xdd, 0x3e, 0xdc, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x77, 0xc7, 0x07,
	0x8e, 0xf1, 0x09, 0x00, 0x00,
}
