// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/cilium/cilium/pkg/k8s/slim/k8s/api/discovery/v1beta1/generated.proto

package v1beta1

import (
	fmt "fmt"

	v1 "github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/meta/v1"
	proto "github.com/gogo/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2884f8c881be40, []int{0}
}
func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Endpoint) GetConditions() *EndpointConditions {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *Endpoint) GetTopology() map[string]string {
	if m != nil {
		return m.Topology
	}
	return nil
}

func (m *Endpoint) GetNodeName() string {
	if m != nil && m.NodeName != nil {
		return *m.NodeName
	}
	return ""
}

func (m *EndpointConditions) Reset()         { *m = EndpointConditions{} }
func (m *EndpointConditions) String() string { return proto.CompactTextString(m) }
func (*EndpointConditions) ProtoMessage()    {}
func (*EndpointConditions) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2884f8c881be40, []int{1}
}
func (m *EndpointConditions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointConditions.Unmarshal(m, b)
}
func (m *EndpointConditions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointConditions.Marshal(b, m, deterministic)
}
func (m *EndpointConditions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointConditions.Merge(m, src)
}
func (m *EndpointConditions) XXX_Size() int {
	return xxx_messageInfo_EndpointConditions.Size(m)
}
func (m *EndpointConditions) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointConditions.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointConditions proto.InternalMessageInfo

func (m *EndpointConditions) GetReady() bool {
	if m != nil && m.Ready != nil {
		return *m.Ready
	}
	return false
}

func (m *EndpointConditions) GetServing() bool {
	if m != nil && m.Serving != nil {
		return *m.Serving
	}
	return false
}

func (m *EndpointConditions) GetTerminating() bool {
	if m != nil && m.Terminating != nil {
		return *m.Terminating
	}
	return false
}

func (m *EndpointHints) Reset()         { *m = EndpointHints{} }
func (m *EndpointHints) String() string { return proto.CompactTextString(m) }
func (*EndpointHints) ProtoMessage()    {}
func (*EndpointHints) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2884f8c881be40, []int{2}
}
func (m *EndpointHints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointHints.Unmarshal(m, b)
}
func (m *EndpointHints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointHints.Marshal(b, m, deterministic)
}
func (m *EndpointHints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointHints.Merge(m, src)
}
func (m *EndpointHints) XXX_Size() int {
	return xxx_messageInfo_EndpointHints.Size(m)
}
func (m *EndpointHints) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointHints.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointHints proto.InternalMessageInfo

func (m *EndpointHints) GetForZones() []*ForZone {
	if m != nil {
		return m.ForZones
	}
	return nil
}

func (m *EndpointPort) Reset()         { *m = EndpointPort{} }
func (m *EndpointPort) String() string { return proto.CompactTextString(m) }
func (*EndpointPort) ProtoMessage()    {}
func (*EndpointPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2884f8c881be40, []int{3}
}
func (m *EndpointPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointPort.Unmarshal(m, b)
}
func (m *EndpointPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointPort.Marshal(b, m, deterministic)
}
func (m *EndpointPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointPort.Merge(m, src)
}
func (m *EndpointPort) XXX_Size() int {
	return xxx_messageInfo_EndpointPort.Size(m)
}
func (m *EndpointPort) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointPort.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointPort proto.InternalMessageInfo

func (m *EndpointPort) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *EndpointPort) GetProtocol() string {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return ""
}

func (m *EndpointPort) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *EndpointSlice) Reset()         { *m = EndpointSlice{} }
func (m *EndpointSlice) String() string { return proto.CompactTextString(m) }
func (*EndpointSlice) ProtoMessage()    {}
func (*EndpointSlice) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2884f8c881be40, []int{4}
}
func (m *EndpointSlice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointSlice.Unmarshal(m, b)
}
func (m *EndpointSlice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointSlice.Marshal(b, m, deterministic)
}
func (m *EndpointSlice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointSlice.Merge(m, src)
}
func (m *EndpointSlice) XXX_Size() int {
	return xxx_messageInfo_EndpointSlice.Size(m)
}
func (m *EndpointSlice) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointSlice.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointSlice proto.InternalMessageInfo

func (m *EndpointSlice) GetMetadata() *v1.ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *EndpointSlice) GetAddressType() string {
	if m != nil && m.AddressType != nil {
		return *m.AddressType
	}
	return ""
}

func (m *EndpointSlice) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *EndpointSlice) GetPorts() []*EndpointPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *EndpointSliceList) Reset()         { *m = EndpointSliceList{} }
func (m *EndpointSliceList) String() string { return proto.CompactTextString(m) }
func (*EndpointSliceList) ProtoMessage()    {}
func (*EndpointSliceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2884f8c881be40, []int{5}
}
func (m *EndpointSliceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointSliceList.Unmarshal(m, b)
}
func (m *EndpointSliceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointSliceList.Marshal(b, m, deterministic)
}
func (m *EndpointSliceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointSliceList.Merge(m, src)
}
func (m *EndpointSliceList) XXX_Size() int {
	return xxx_messageInfo_EndpointSliceList.Size(m)
}
func (m *EndpointSliceList) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointSliceList.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointSliceList proto.InternalMessageInfo

func (m *EndpointSliceList) GetMetadata() *v1.ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *EndpointSliceList) GetItems() []*EndpointSlice {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ForZone) Reset()         { *m = ForZone{} }
func (m *ForZone) String() string { return proto.CompactTextString(m) }
func (*ForZone) ProtoMessage()    {}
func (*ForZone) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2884f8c881be40, []int{6}
}
func (m *ForZone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForZone.Unmarshal(m, b)
}
func (m *ForZone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForZone.Marshal(b, m, deterministic)
}
func (m *ForZone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForZone.Merge(m, src)
}
func (m *ForZone) XXX_Size() int {
	return xxx_messageInfo_ForZone.Size(m)
}
func (m *ForZone) XXX_DiscardUnknown() {
	xxx_messageInfo_ForZone.DiscardUnknown(m)
}

var xxx_messageInfo_ForZone proto.InternalMessageInfo

func (m *ForZone) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Endpoint)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.discovery.v1beta1.Endpoint")
	proto.RegisterMapType((map[string]string)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.discovery.v1beta1.Endpoint.TopologyEntry")
	proto.RegisterType((*EndpointConditions)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.discovery.v1beta1.EndpointConditions")
	proto.RegisterType((*EndpointHints)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.discovery.v1beta1.EndpointHints")
	proto.RegisterType((*EndpointPort)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.discovery.v1beta1.EndpointPort")
	proto.RegisterType((*EndpointSlice)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.discovery.v1beta1.EndpointSlice")
	proto.RegisterType((*EndpointSliceList)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.discovery.v1beta1.EndpointSliceList")
	proto.RegisterType((*ForZone)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.discovery.v1beta1.ForZone")
}

func init() {
	proto.RegisterFile("github.com/cilium/cilium/pkg/k8s/slim/k8s/api/discovery/v1beta1/generated.proto", fileDescriptor_db2884f8c881be40)
}

var fileDescriptor_db2884f8c881be40 = []byte{
	// 588 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xdf, 0x6b, 0xdb, 0x30,
	0x10, 0xc7, 0x71, 0xd2, 0xac, 0x8e, 0xb2, 0xc2, 0x26, 0xf6, 0x60, 0xc2, 0x06, 0xc1, 0x4f, 0x79,
	0x92, 0x69, 0x1e, 0x46, 0xd9, 0x1e, 0xba, 0x75, 0xb4, 0x74, 0xb0, 0xb6, 0x43, 0x2d, 0x0c, 0xca,
	0x18, 0xa8, 0xf6, 0xd5, 0xd1, 0x62, 0x4b, 0x46, 0x52, 0x0c, 0xf9, 0x4b, 0xf7, 0xb8, 0x3f, 0x60,
	0xff, 0xc4, 0x90, 0xfc, 0x23, 0x69, 0x53, 0x18, 0x59, 0xf2, 0xe4, 0x3b, 0xf9, 0xee, 0x73, 0x77,
	0x5f, 0x9f, 0x30, 0xba, 0x4a, 0xb9, 0x99, 0xce, 0xef, 0x48, 0x2c, 0xf3, 0x28, 0xe6, 0x19, 0x9f,
	0xb7, 0x8f, 0x62, 0x96, 0x46, 0xb3, 0x23, 0x1d, 0xe9, 0x8c, 0xe7, 0xce, 0x60, 0x05, 0x8f, 0x12,
	0xae, 0x63, 0x59, 0x82, 0x5a, 0x44, 0xe5, 0xe1, 0x1d, 0x18, 0x76, 0x18, 0xa5, 0x20, 0x40, 0x31,
	0x03, 0x09, 0x29, 0x94, 0x34, 0x12, 0x1f, 0x2f, 0x81, 0xa4, 0x22, 0x35, 0x8f, 0x62, 0x96, 0x92,
	0xd9, 0x91, 0x26, 0x16, 0xe8, 0x0c, 0x56, 0x70, 0xd2, 0x02, 0x49, 0x0d, 0x1c, 0x9e, 0x6e, 0xd6,
	0x51, 0x2c, 0x15, 0x44, 0xe5, 0x5a, 0x1f, 0xc3, 0xb3, 0x8d, 0x30, 0x3a, 0xca, 0xc1, 0xb0, 0xa7,
	0x38, 0x36, 0x82, 0x70, 0x69, 0x83, 0x72, 0x16, 0x4f, 0xb9, 0xb0, 0xc3, 0x5b, 0x84, 0x9a, 0x0b,
	0xc3, 0x73, 0x58, 0x4b, 0x78, 0xfb, 0xaf, 0x04, 0x1d, 0x4f, 0x21, 0x67, 0x8f, 0xf3, 0xc2, 0x3f,
	0x1d, 0xe4, 0x9f, 0x8a, 0xa4, 0x90, 0x5c, 0x18, 0xfc, 0x1a, 0xf5, 0x59, 0x92, 0x28, 0xd0, 0x1a,
	0x74, 0xe0, 0x8d, 0xba, 0xe3, 0x3e, 0x5d, 0x1e, 0x60, 0x8d, 0x50, 0x2c, 0x45, 0xc2, 0x0d, 0x97,
	0x42, 0x07, 0x9d, 0x91, 0x37, 0x1e, 0x4c, 0xae, 0xc9, 0x96, 0xc2, 0x93, 0xa6, 0xf8, 0xa7, 0x16,
	0x4d, 0x57, 0xca, 0x60, 0x8d, 0x7c, 0x23, 0x0b, 0x99, 0xc9, 0x74, 0x11, 0xf4, 0x46, 0xdd, 0xf1,
	0x60, 0xf2, 0x6d, 0x67, 0x25, 0xc9, 0x4d, 0x4d, 0x3e, 0x15, 0x46, 0x2d, 0x68, 0x5b, 0x08, 0x0f,
	0x91, 0x2f, 0x64, 0x02, 0x97, 0x2c, 0x87, 0xe0, 0xd9, 0xc8, 0x1b, 0xf7, 0x69, 0xeb, 0x0f, 0xdf,
	0xa3, 0x83, 0x07, 0x69, 0xf8, 0x05, 0xea, 0xce, 0x60, 0x11, 0x78, 0x2e, 0xce, 0x9a, 0xf8, 0x15,
	0xea, 0x95, 0x2c, 0x9b, 0x83, 0xd3, 0xa8, 0x4f, 0x2b, 0xe7, 0x5d, 0xe7, 0xc8, 0x0b, 0xef, 0x11,
	0x5e, 0x9f, 0xd7, 0xc6, 0x2b, 0x60, 0x49, 0xc5, 0xf0, 0x69, 0xe5, 0xe0, 0x00, 0xed, 0x6b, 0x50,
	0x25, 0x17, 0xa9, 0xe3, 0xf8, 0xb4, 0x71, 0xf1, 0x08, 0x0d, 0x0c, 0xa8, 0x9c, 0x0b, 0x66, 0xec,
	0xdb, 0xae, 0x7b, 0xbb, 0x7a, 0x14, 0xce, 0xd1, 0x41, 0x53, 0xe7, 0x9c, 0x0b, 0xa3, 0x71, 0x82,
	0xfc, 0x7b, 0xa9, 0x6e, 0xa5, 0xa8, 0x3f, 0xec, 0x60, 0x72, 0xbe, 0xb5, 0x8c, 0x67, 0x15, 0x90,
	0xb6, 0xe4, 0x90, 0xa2, 0xe7, 0x4d, 0xd9, 0xaf, 0x52, 0x19, 0x8c, 0xd1, 0x9e, 0xb0, 0x1a, 0x56,
	0xda, 0x38, 0xdb, 0x6a, 0xeb, 0x36, 0x2f, 0x96, 0x59, 0xad, 0x4f, 0xeb, 0xdb, 0xf8, 0x42, 0x2a,
	0xe3, 0x26, 0xea, 0x51, 0x67, 0x87, 0xbf, 0x3b, 0xcb, 0x59, 0xae, 0x33, 0x1e, 0x03, 0xfe, 0x81,
	0x7c, 0x7b, 0x6d, 0x12, 0x66, 0x98, 0x23, 0x0f, 0x26, 0x27, 0x9b, 0xcd, 0xa2, 0x89, 0xcd, 0x27,
	0xe5, 0x21, 0xb9, 0xba, 0xfb, 0x09, 0xb1, 0xb9, 0x00, 0xc3, 0x68, 0xcb, 0xb4, 0xf2, 0xd6, 0x4b,
	0x7f, 0xb3, 0x28, 0x20, 0xd8, 0x73, 0x4d, 0xae, 0x1e, 0xe1, 0x14, 0xf5, 0xa1, 0x6e, 0xc9, 0x5e,
	0x04, 0x2b, 0xe7, 0xe7, 0x9d, 0x6d, 0x25, 0x5d, 0xb2, 0x71, 0x8c, 0x7a, 0x56, 0x04, 0x1d, 0x74,
	0x5d, 0x91, 0x8b, 0x9d, 0x15, 0xb1, 0x9f, 0x87, 0x56, 0xec, 0xf0, 0x97, 0x87, 0x5e, 0x3e, 0x50,
	0xf8, 0x0b, 0xd7, 0x06, 0x7f, 0x5f, 0x53, 0xf9, 0xc3, 0xff, 0xaa, 0x6c, 0x79, 0x8f, 0x34, 0x4e,
	0x50, 0x8f, 0x1b, 0xc8, 0x1b, 0xf5, 0x2e, 0x77, 0x36, 0x98, 0x1b, 0x80, 0x56, 0xf0, 0xf0, 0x0d,
	0xda, 0xaf, 0x97, 0xf4, 0xa9, 0x55, 0x3c, 0xf9, 0x78, 0x7b, 0xbc, 0xe5, 0x7f, 0xe8, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xa7, 0xdf, 0xf2, 0x18, 0xc9, 0x06, 0x00, 0x00,
}
