// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/cilium/cilium/pkg/k8s/slim/k8s/api/networking/v1/generated.proto

package v1

import (
	fmt "fmt"

	v1 "github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/meta/v1"
	intstr "github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/util/intstr"
	proto "github.com/gogo/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *IPBlock) Reset()         { *m = IPBlock{} }
func (m *IPBlock) String() string { return proto.CompactTextString(m) }
func (*IPBlock) ProtoMessage()    {}
func (*IPBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3be2d57d520df2, []int{0}
}
func (m *IPBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPBlock.Unmarshal(m, b)
}
func (m *IPBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPBlock.Marshal(b, m, deterministic)
}
func (m *IPBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPBlock.Merge(m, src)
}
func (m *IPBlock) XXX_Size() int {
	return xxx_messageInfo_IPBlock.Size(m)
}
func (m *IPBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_IPBlock.DiscardUnknown(m)
}

var xxx_messageInfo_IPBlock proto.InternalMessageInfo

func (m *IPBlock) GetCidr() string {
	if m != nil && m.Cidr != nil {
		return *m.Cidr
	}
	return ""
}

func (m *IPBlock) GetExcept() []string {
	if m != nil {
		return m.Except
	}
	return nil
}

func (m *NetworkPolicy) Reset()         { *m = NetworkPolicy{} }
func (m *NetworkPolicy) String() string { return proto.CompactTextString(m) }
func (*NetworkPolicy) ProtoMessage()    {}
func (*NetworkPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3be2d57d520df2, []int{1}
}
func (m *NetworkPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkPolicy.Unmarshal(m, b)
}
func (m *NetworkPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkPolicy.Marshal(b, m, deterministic)
}
func (m *NetworkPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkPolicy.Merge(m, src)
}
func (m *NetworkPolicy) XXX_Size() int {
	return xxx_messageInfo_NetworkPolicy.Size(m)
}
func (m *NetworkPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkPolicy proto.InternalMessageInfo

func (m *NetworkPolicy) GetMetadata() *v1.ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *NetworkPolicy) GetSpec() *NetworkPolicySpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *NetworkPolicyEgressRule) Reset()         { *m = NetworkPolicyEgressRule{} }
func (m *NetworkPolicyEgressRule) String() string { return proto.CompactTextString(m) }
func (*NetworkPolicyEgressRule) ProtoMessage()    {}
func (*NetworkPolicyEgressRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3be2d57d520df2, []int{2}
}
func (m *NetworkPolicyEgressRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkPolicyEgressRule.Unmarshal(m, b)
}
func (m *NetworkPolicyEgressRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkPolicyEgressRule.Marshal(b, m, deterministic)
}
func (m *NetworkPolicyEgressRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkPolicyEgressRule.Merge(m, src)
}
func (m *NetworkPolicyEgressRule) XXX_Size() int {
	return xxx_messageInfo_NetworkPolicyEgressRule.Size(m)
}
func (m *NetworkPolicyEgressRule) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkPolicyEgressRule.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkPolicyEgressRule proto.InternalMessageInfo

func (m *NetworkPolicyEgressRule) GetPorts() []*NetworkPolicyPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *NetworkPolicyEgressRule) GetTo() []*NetworkPolicyPeer {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *NetworkPolicyIngressRule) Reset()         { *m = NetworkPolicyIngressRule{} }
func (m *NetworkPolicyIngressRule) String() string { return proto.CompactTextString(m) }
func (*NetworkPolicyIngressRule) ProtoMessage()    {}
func (*NetworkPolicyIngressRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3be2d57d520df2, []int{3}
}
func (m *NetworkPolicyIngressRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkPolicyIngressRule.Unmarshal(m, b)
}
func (m *NetworkPolicyIngressRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkPolicyIngressRule.Marshal(b, m, deterministic)
}
func (m *NetworkPolicyIngressRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkPolicyIngressRule.Merge(m, src)
}
func (m *NetworkPolicyIngressRule) XXX_Size() int {
	return xxx_messageInfo_NetworkPolicyIngressRule.Size(m)
}
func (m *NetworkPolicyIngressRule) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkPolicyIngressRule.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkPolicyIngressRule proto.InternalMessageInfo

func (m *NetworkPolicyIngressRule) GetPorts() []*NetworkPolicyPort {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *NetworkPolicyIngressRule) GetFrom() []*NetworkPolicyPeer {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *NetworkPolicyList) Reset()         { *m = NetworkPolicyList{} }
func (m *NetworkPolicyList) String() string { return proto.CompactTextString(m) }
func (*NetworkPolicyList) ProtoMessage()    {}
func (*NetworkPolicyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3be2d57d520df2, []int{4}
}
func (m *NetworkPolicyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkPolicyList.Unmarshal(m, b)
}
func (m *NetworkPolicyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkPolicyList.Marshal(b, m, deterministic)
}
func (m *NetworkPolicyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkPolicyList.Merge(m, src)
}
func (m *NetworkPolicyList) XXX_Size() int {
	return xxx_messageInfo_NetworkPolicyList.Size(m)
}
func (m *NetworkPolicyList) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkPolicyList.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkPolicyList proto.InternalMessageInfo

func (m *NetworkPolicyList) GetMetadata() *v1.ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *NetworkPolicyList) GetItems() []*NetworkPolicy {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *NetworkPolicyPeer) Reset()         { *m = NetworkPolicyPeer{} }
func (m *NetworkPolicyPeer) String() string { return proto.CompactTextString(m) }
func (*NetworkPolicyPeer) ProtoMessage()    {}
func (*NetworkPolicyPeer) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3be2d57d520df2, []int{5}
}
func (m *NetworkPolicyPeer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkPolicyPeer.Unmarshal(m, b)
}
func (m *NetworkPolicyPeer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkPolicyPeer.Marshal(b, m, deterministic)
}
func (m *NetworkPolicyPeer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkPolicyPeer.Merge(m, src)
}
func (m *NetworkPolicyPeer) XXX_Size() int {
	return xxx_messageInfo_NetworkPolicyPeer.Size(m)
}
func (m *NetworkPolicyPeer) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkPolicyPeer.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkPolicyPeer proto.InternalMessageInfo

func (m *NetworkPolicyPeer) GetPodSelector() *v1.LabelSelector {
	if m != nil {
		return m.PodSelector
	}
	return nil
}

func (m *NetworkPolicyPeer) GetNamespaceSelector() *v1.LabelSelector {
	if m != nil {
		return m.NamespaceSelector
	}
	return nil
}

func (m *NetworkPolicyPeer) GetIpBlock() *IPBlock {
	if m != nil {
		return m.IpBlock
	}
	return nil
}

func (m *NetworkPolicyPort) Reset()         { *m = NetworkPolicyPort{} }
func (m *NetworkPolicyPort) String() string { return proto.CompactTextString(m) }
func (*NetworkPolicyPort) ProtoMessage()    {}
func (*NetworkPolicyPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3be2d57d520df2, []int{6}
}
func (m *NetworkPolicyPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkPolicyPort.Unmarshal(m, b)
}
func (m *NetworkPolicyPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkPolicyPort.Marshal(b, m, deterministic)
}
func (m *NetworkPolicyPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkPolicyPort.Merge(m, src)
}
func (m *NetworkPolicyPort) XXX_Size() int {
	return xxx_messageInfo_NetworkPolicyPort.Size(m)
}
func (m *NetworkPolicyPort) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkPolicyPort.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkPolicyPort proto.InternalMessageInfo

func (m *NetworkPolicyPort) GetProtocol() string {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return ""
}

func (m *NetworkPolicyPort) GetPort() *intstr.IntOrString {
	if m != nil {
		return m.Port
	}
	return nil
}

func (m *NetworkPolicyPort) GetEndPort() int32 {
	if m != nil && m.EndPort != nil {
		return *m.EndPort
	}
	return 0
}

func (m *NetworkPolicySpec) Reset()         { *m = NetworkPolicySpec{} }
func (m *NetworkPolicySpec) String() string { return proto.CompactTextString(m) }
func (*NetworkPolicySpec) ProtoMessage()    {}
func (*NetworkPolicySpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d3be2d57d520df2, []int{7}
}
func (m *NetworkPolicySpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkPolicySpec.Unmarshal(m, b)
}
func (m *NetworkPolicySpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkPolicySpec.Marshal(b, m, deterministic)
}
func (m *NetworkPolicySpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkPolicySpec.Merge(m, src)
}
func (m *NetworkPolicySpec) XXX_Size() int {
	return xxx_messageInfo_NetworkPolicySpec.Size(m)
}
func (m *NetworkPolicySpec) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkPolicySpec.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkPolicySpec proto.InternalMessageInfo

func (m *NetworkPolicySpec) GetPodSelector() *v1.LabelSelector {
	if m != nil {
		return m.PodSelector
	}
	return nil
}

func (m *NetworkPolicySpec) GetIngress() []*NetworkPolicyIngressRule {
	if m != nil {
		return m.Ingress
	}
	return nil
}

func (m *NetworkPolicySpec) GetEgress() []*NetworkPolicyEgressRule {
	if m != nil {
		return m.Egress
	}
	return nil
}

func (m *NetworkPolicySpec) GetPolicyTypes() []string {
	if m != nil {
		return m.PolicyTypes
	}
	return nil
}

func init() {
	proto.RegisterType((*IPBlock)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.networking.v1.IPBlock")
	proto.RegisterType((*NetworkPolicy)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.networking.v1.NetworkPolicy")
	proto.RegisterType((*NetworkPolicyEgressRule)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.networking.v1.NetworkPolicyEgressRule")
	proto.RegisterType((*NetworkPolicyIngressRule)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.networking.v1.NetworkPolicyIngressRule")
	proto.RegisterType((*NetworkPolicyList)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.networking.v1.NetworkPolicyList")
	proto.RegisterType((*NetworkPolicyPeer)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.networking.v1.NetworkPolicyPeer")
	proto.RegisterType((*NetworkPolicyPort)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.networking.v1.NetworkPolicyPort")
	proto.RegisterType((*NetworkPolicySpec)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.api.networking.v1.NetworkPolicySpec")
}

func init() {
	proto.RegisterFile("github.com/cilium/cilium/pkg/k8s/slim/k8s/api/networking/v1/generated.proto", fileDescriptor_5d3be2d57d520df2)
}

var fileDescriptor_5d3be2d57d520df2 = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x96, 0x4f, 0x4f, 0x14, 0x31,
	0x18, 0xc6, 0x33, 0xb3, 0x0b, 0x0b, 0x25, 0x1e, 0xe8, 0x41, 0x27, 0x9c, 0x36, 0x73, 0xe2, 0xd4,
	0x09, 0x26, 0x1a, 0x12, 0x62, 0x62, 0x88, 0x68, 0x40, 0x05, 0x52, 0xf0, 0xa2, 0x86, 0xd8, 0xed,
	0xbc, 0x0e, 0x75, 0xfe, 0xb4, 0x69, 0xbb, 0x28, 0x5f, 0xc8, 0xef, 0x63, 0xfc, 0x00, 0x5e, 0xfc,
	0x1a, 0x26, 0xa6, 0x9d, 0xd9, 0x65, 0xff, 0x90, 0x98, 0x65, 0x47, 0x4e, 0xd3, 0x6e, 0xa7, 0xbf,
	0xf7, 0x7d, 0xda, 0x27, 0xcf, 0x0e, 0x7a, 0x9d, 0x09, 0x7b, 0x39, 0x1c, 0x10, 0x2e, 0xcb, 0x84,
	0x8b, 0x42, 0x0c, 0xc7, 0x0f, 0x95, 0x67, 0x49, 0xbe, 0x6b, 0x12, 0x53, 0x88, 0xd2, 0x0f, 0x98,
	0x12, 0x49, 0x05, 0xf6, 0xab, 0xd4, 0xb9, 0xa8, 0xb2, 0xe4, 0x6a, 0x27, 0xc9, 0xa0, 0x02, 0xcd,
	0x2c, 0xa4, 0x44, 0x69, 0x69, 0x25, 0xde, 0xbb, 0x81, 0x91, 0x9a, 0x32, 0x7a, 0xa8, 0x3c, 0x23,
	0xf9, 0xae, 0x21, 0x0e, 0xe6, 0x07, 0x4c, 0x09, 0x72, 0x03, 0x23, 0x57, 0x3b, 0x5b, 0x07, 0x8b,
	0x75, 0xc2, 0xa5, 0x86, 0x5b, 0x7a, 0xd8, 0x7a, 0xb9, 0x10, 0xc6, 0x24, 0x25, 0x58, 0x76, 0x1b,
	0xe7, 0x68, 0x41, 0xce, 0xd0, 0x8a, 0x22, 0x11, 0x95, 0x35, 0x56, 0xcf, 0xb1, 0xdc, 0x5b, 0x44,
	0x48, 0xf7, 0x62, 0xc9, 0xf8, 0xa5, 0xa8, 0x40, 0x5f, 0x7b, 0x8c, 0x1e, 0x56, 0x56, 0x94, 0x30,
	0xb7, 0xe1, 0xe9, 0xbf, 0x36, 0x18, 0x7e, 0x09, 0x25, 0x9b, 0xdd, 0x17, 0x3f, 0x41, 0xbd, 0xc3,
	0xd3, 0xfd, 0x42, 0xf2, 0x1c, 0x63, 0xd4, 0xe5, 0x22, 0xd5, 0x51, 0xd0, 0x0f, 0xb6, 0xd7, 0xa9,
	0x1f, 0xe3, 0x87, 0x68, 0x15, 0xbe, 0x71, 0x50, 0x36, 0x0a, 0xfb, 0x9d, 0xed, 0x75, 0xda, 0xcc,
	0xe2, 0x9f, 0x01, 0x7a, 0x70, 0x5c, 0x5f, 0xc6, 0xa9, 0x2c, 0x04, 0xbf, 0xc6, 0x17, 0x68, 0xcd,
	0x1d, 0x4c, 0xca, 0x2c, 0xf3, 0x84, 0x8d, 0xc7, 0xfb, 0x64, 0xa1, 0xcb, 0x35, 0xc4, 0xed, 0x27,
	0x57, 0x3b, 0xe4, 0x64, 0xf0, 0x05, 0xb8, 0x7d, 0x0b, 0x96, 0xd1, 0x31, 0x13, 0x0f, 0x50, 0xd7,
	0x28, 0xe0, 0x51, 0xe8, 0xd9, 0xc7, 0x64, 0x09, 0xe3, 0x90, 0xa9, 0xce, 0xcf, 0x14, 0x70, 0xea,
	0xd9, 0xf1, 0xaf, 0x00, 0x3d, 0x9a, 0x5a, 0x3b, 0xc8, 0x34, 0x18, 0x43, 0x87, 0x05, 0xe0, 0x14,
	0xad, 0x28, 0xa9, 0xad, 0x89, 0x82, 0x7e, 0xa7, 0xdd, 0x06, 0x4e, 0xa5, 0xb6, 0xb4, 0x86, 0xe3,
	0x0b, 0x14, 0x5a, 0xe9, 0xcf, 0xba, 0xdd, 0x12, 0x00, 0x9a, 0x86, 0x56, 0xc6, 0xbf, 0x03, 0x14,
	0x4d, 0xad, 0x1c, 0x56, 0xf7, 0x2d, 0x71, 0x80, 0xba, 0x9f, 0xb5, 0x2c, 0xff, 0x93, 0x48, 0xcf,
	0x76, 0xf6, 0xdc, 0x9c, 0x5a, 0x7b, 0x23, 0x8c, 0xc5, 0x1f, 0xe7, 0x2c, 0xfa, 0xfc, 0xae, 0x16,
	0x75, 0xbc, 0x19, 0x83, 0x7e, 0x42, 0x2b, 0xc2, 0x42, 0x69, 0x1a, 0x61, 0x47, 0xed, 0x09, 0xa3,
	0x35, 0x38, 0xfe, 0x11, 0xce, 0xa8, 0x72, 0x8a, 0x71, 0x86, 0x36, 0x94, 0x4c, 0xcf, 0xa0, 0x00,
	0x6e, 0xa5, 0x6e, 0x84, 0x1d, 0xdc, 0x59, 0x18, 0x1b, 0x40, 0x31, 0x82, 0xd1, 0x49, 0x32, 0x36,
	0x68, 0xb3, 0x62, 0x25, 0x18, 0xc5, 0x38, 0x8c, 0xcb, 0x85, 0x6d, 0x96, 0x9b, 0xe7, 0xe3, 0x0b,
	0xd4, 0x13, 0xca, 0xe7, 0x53, 0xd4, 0xf1, 0xa5, 0x5e, 0x2c, 0x75, 0xae, 0x4d, 0xd6, 0xd1, 0x11,
	0x34, 0xfe, 0x3e, 0xeb, 0x14, 0x67, 0x55, 0xbc, 0x85, 0xd6, 0x7c, 0x3c, 0x72, 0x59, 0x34, 0x71,
	0x38, 0x9e, 0xe3, 0x0f, 0xa8, 0xeb, 0x8c, 0xdc, 0x28, 0x7f, 0xb5, 0xa8, 0x72, 0x97, 0xfa, 0xa4,
	0x4e, 0x7d, 0x72, 0x58, 0xd9, 0x13, 0x7d, 0x66, 0xb5, 0xa8, 0x32, 0xea, 0xa1, 0x38, 0x42, 0x3d,
	0xa8, 0x52, 0xd7, 0x83, 0x97, 0xbb, 0x42, 0x47, 0xd3, 0xf8, 0xcf, 0xec, 0xe5, 0xbb, 0xdc, 0xba,
	0xbf, 0xcb, 0x97, 0xa8, 0x27, 0xea, 0xa8, 0x68, 0xfc, 0xfd, 0xae, 0x3d, 0x7f, 0x4f, 0x64, 0x10,
	0x1d, 0x55, 0xc1, 0x05, 0x5a, 0x85, 0xba, 0x5e, 0xc7, 0xd7, 0x3b, 0x6f, 0xaf, 0xde, 0x4d, 0xaa,
	0xd3, 0xa6, 0x06, 0xee, 0xbb, 0x73, 0x74, 0x6b, 0xe7, 0xd7, 0x0a, 0x4c, 0xd4, 0xf5, 0x7f, 0x76,
	0x93, 0x3f, 0xed, 0x3f, 0x7b, 0xbf, 0xb7, 0xc4, 0x87, 0xcf, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x77, 0x2e, 0x10, 0xcd, 0x36, 0x09, 0x00, 0x00,
}
