// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/apiextensions/v1/generated.proto

package v1

import (
	fmt "fmt"

	v1 "github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/meta/v1"
	proto "github.com/gogo/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *CustomResourceDefinition) Reset()         { *m = CustomResourceDefinition{} }
func (m *CustomResourceDefinition) String() string { return proto.CompactTextString(m) }
func (*CustomResourceDefinition) ProtoMessage()    {}
func (*CustomResourceDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae25e910fba1c55, []int{0}
}
func (m *CustomResourceDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomResourceDefinition.Unmarshal(m, b)
}
func (m *CustomResourceDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomResourceDefinition.Marshal(b, m, deterministic)
}
func (m *CustomResourceDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomResourceDefinition.Merge(m, src)
}
func (m *CustomResourceDefinition) XXX_Size() int {
	return xxx_messageInfo_CustomResourceDefinition.Size(m)
}
func (m *CustomResourceDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomResourceDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_CustomResourceDefinition proto.InternalMessageInfo

func (m *CustomResourceDefinition) GetMetadata() *v1.ObjectMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CustomResourceDefinitionList) Reset()         { *m = CustomResourceDefinitionList{} }
func (m *CustomResourceDefinitionList) String() string { return proto.CompactTextString(m) }
func (*CustomResourceDefinitionList) ProtoMessage()    {}
func (*CustomResourceDefinitionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae25e910fba1c55, []int{1}
}
func (m *CustomResourceDefinitionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomResourceDefinitionList.Unmarshal(m, b)
}
func (m *CustomResourceDefinitionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomResourceDefinitionList.Marshal(b, m, deterministic)
}
func (m *CustomResourceDefinitionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomResourceDefinitionList.Merge(m, src)
}
func (m *CustomResourceDefinitionList) XXX_Size() int {
	return xxx_messageInfo_CustomResourceDefinitionList.Size(m)
}
func (m *CustomResourceDefinitionList) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomResourceDefinitionList.DiscardUnknown(m)
}

var xxx_messageInfo_CustomResourceDefinitionList proto.InternalMessageInfo

func (m *CustomResourceDefinitionList) GetMetadata() *v1.ListMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *CustomResourceDefinitionList) GetItems() []*CustomResourceDefinition {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*CustomResourceDefinition)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.apiextensions.v1.CustomResourceDefinition")
	proto.RegisterType((*CustomResourceDefinitionList)(nil), "github.com.cilium.cilium.pkg.k8s.slim.k8s.apis.apiextensions.v1.CustomResourceDefinitionList")
}

func init() {
	proto.RegisterFile("github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/apiextensions/v1/generated.proto", fileDescriptor_2ae25e910fba1c55)
}

var fileDescriptor_2ae25e910fba1c55 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xa9, 0x22, 0x48, 0x7a, 0xcb, 0x29, 0x14, 0x0f, 0xa5, 0xa7, 0x9e, 0x26, 0xa4, 0x07,
	0xe9, 0xad, 0x5a, 0xc5, 0x93, 0x52, 0xc8, 0x4d, 0x11, 0x61, 0xbb, 0x1d, 0x93, 0x31, 0xdd, 0xdd,
	0x90, 0x99, 0x04, 0xf5, 0x3f, 0xfb, 0x1f, 0x64, 0x53, 0xac, 0xd4, 0x5a, 0xa4, 0xf6, 0xb2, 0x33,
	0x87, 0x79, 0xdf, 0x7b, 0xbb, 0x3b, 0xc1, 0x2c, 0x23, 0xc9, 0xeb, 0x39, 0x68, 0x67, 0x62, 0x4d,
	0x4b, 0xaa, 0xd7, 0xa5, 0x2c, 0xb2, 0xb8, 0x18, 0x73, 0xcc, 0x4b, 0x32, 0x6d, 0xa3, 0x4a, 0x6a,
	0x0f, 0x7c, 0x15, 0xb4, 0x4c, 0xce, 0x72, 0xdc, 0x24, 0x71, 0x86, 0x16, 0x2b, 0x25, 0xb8, 0x80,
	0xb2, 0x72, 0xe2, 0xc2, 0xc9, 0x37, 0x10, 0x56, 0xa4, 0xaf, 0x52, 0x16, 0x19, 0x14, 0x63, 0x06,
	0x0f, 0x6c, 0x1b, 0x0f, 0x84, 0x0d, 0x20, 0x34, 0x49, 0xef, 0x66, 0xcf, 0x44, 0x06, 0x45, 0xfd,
	0x12, 0xa4, 0xe7, 0x27, 0x80, 0x9c, 0x1f, 0x32, 0x4a, 0xe7, 0x64, 0xb1, 0x7a, 0x6b, 0x11, 0x55,
	0x6d, 0x85, 0x0c, 0x6e, 0x09, 0xce, 0xff, 0x12, 0xb0, 0xce, 0xd1, 0xa8, 0x9f, 0xba, 0xc1, 0x7b,
	0x10, 0x5d, 0xd5, 0x2c, 0xce, 0xa4, 0xc8, 0xae, 0xae, 0x34, 0x5e, 0xe3, 0x33, 0x59, 0x12, 0x72,
	0x36, 0x7c, 0x0a, 0x4e, 0x7d, 0xbe, 0x85, 0x12, 0x15, 0x75, 0xfa, 0x9d, 0x61, 0x77, 0x34, 0x85,
	0x3d, 0x1f, 0xc8, 0xeb, 0xa1, 0x49, 0x60, 0x36, 0x7f, 0x41, 0x2d, 0x77, 0x28, 0x2a, 0x5d, 0x33,
	0x07, 0x1f, 0x9d, 0xe0, 0x6c, 0x97, 0xf9, 0x2d, 0xb1, 0x84, 0x8f, 0x5b, 0x01, 0x2e, 0xfe, 0x1b,
	0xc0, 0xf3, 0x36, 0xed, 0x43, 0x17, 0x9c, 0x90, 0xa0, 0xe1, 0xe8, 0xa8, 0x7f, 0x3c, 0xec, 0x8e,
	0xee, 0xe1, 0xc0, 0xcf, 0x87, 0x5d, 0x77, 0x49, 0x57, 0x3e, 0xd3, 0xcb, 0x87, 0xc9, 0x81, 0x0b,
	0xfb, 0x19, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x4d, 0x81, 0x2a, 0xf2, 0x02, 0x00, 0x00,
}
